function getDrinkData() {
    return [
      //양조주 50개
      {
        name: "버드와이저",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5,
        rating: 4.1,
        description: "세계적으로 유명한 맥주로, 가벼운 탄산과 부드러운 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "부드럽고 시원한 맛",
        image: "https://i3n.news1.kr/system/photos/2021/1/15/4576974/high.jpg"
      },
      {
        name: "하이네켄",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "네덜란드",
        alcohol: 5,
        rating: 4.2,
        description: "네덜란드의 대표적인 맥주로, 깔끔하고 상쾌한 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "깔끔하고 청량한 맛",
        image: "https://i.pinimg.com/564x/13/e1/3e/13e13ed8e5e93bbe19f93b87bfe2c61c.jpg"
      },
      {
        name: "아사히 슈퍼 드라이",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5,
        rating: 4.3,
        description: "일본의 대표 맥주로, 깔끔하고 청량한 드라이한 맛이 특징입니다.",
        price: 3200,
        tasteDescription: "드라이하고 깔끔한 맛",
        image: "https://cdn.veluga.kr/files/supplier/287/drinks/7.%E1%84%8C%E1%85%AE%E1%84%85%E1%85%A9%E1%86%BA%E1%84%83%E1%85%A6%E1%84%8B%E1%85%A1%E1%84%89%E1%85%A1%E1%84%92%E1%85%B5%E1%84%8C%E1%85%AE%E1%84%85%E1%85%B2_%E1%84%8B%E1%85%A1%E1%84%89%E1%85%A1%E1%84%92%E1%85%B5_%E1%84%89%E1%85%AE%E1%84%91%E1%85%A5_%E1%84%83%E1%85%B3%E1%84%85%E1%85%A1%E1%84%8B%E1%85%B5.png"
      },
      {
        name: "호가든",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 4.9,
        rating: 4.6,
        description: "벨기에의 대표적인 밀맥주로, 부드럽고 상쾌한 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "부드럽고 상쾌한 밀 맛",
        image: "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyNDA3MDJfOTgg%2FMDAxNzE5OTA4NDE5MDMy.lCPq2NcgELINpyc4iHxlKRz_R_a2XQngcpkUVz2MuFMg.BQxMyc1p0i96k19fv-LfhhWz1zqmMEf_SzWBzIVUfhkg.JPEG%2FIMG_0177.jpg&type=sc960_832"
      },
      {
        name: "기네스",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "아일랜드",
        alcohol: 4.2,
        rating: 4.8,
        description: "진한 색상과 부드러운 크림 거품, 깊고 진한 맛이 특징인 맥주입니다.",
        price: 5000,
        tasteDescription: "깊고 진한 몰트 맛",
        image: "https://cdn.imweb.me/thumbnail/20201222/9be70d4e2232b.jpg"
      },
      {
        name: "카스 프레시",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "대한민국",
        alcohol: 4.5,
        rating: 4.0,
        description: "한국에서 가장 인기 있는 라거 맥주로, 시원하고 청량한 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "시원하고 청량한 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/24/10/8801858011024_1.png"
      },
      {
        name: "테라",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "대한민국",
        alcohol: 4.6,
        rating: 4.2,
        description: "청정 라거로 유명한 테라는 부드럽고 깔끔한 맛을 제공합니다.",
        price: 3200,
        tasteDescription: "부드럽고 깔끔한 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/11/00/8801119770011_1.png"
      },
      {
        name: "산 미구엘",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "필리핀",
        alcohol: 5,
        rating: 4.1,
        description: "필리핀에서 가장 인기 있는 맥주로, 가벼운 맛과 청량감이 특징입니다.",
        price: 2800,
        tasteDescription: "청량하고 상쾌한 맛",
        image: "https://theliquor.net/wp-content/uploads/2020/06/pilsen-e1591228861468.png"
      },
      {
        name: "코로나",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "멕시코",
        alcohol: 4.6,
        rating: 4.5,
        description: "라임과 함께 마시면 더욱 상쾌한 멕시코 대표 맥주입니다.",
        price: 4000,
        tasteDescription: "상쾌하고 가벼운 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/13/50/8801021215013_1.png"
      },
      {
        name: "블루문",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5.4,
        rating: 4.4,
        description: "미국의 인기 밀맥주로, 부드럽고 상큼한 오렌지 향이 특징입니다.",
        price: 4500,
        tasteDescription: "부드러운 밀과 상큼한 오렌지 향",
        image: "https://pimg.mk.co.kr/meet/neds/2018/06/image_readtop_2018_380078_15290964623352759.jpg"
      },
      {
        name: "칭따오",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "중국",
        alcohol: 4.7,
        rating: 4.3,
        description: "중국의 대표 맥주로, 깔끔하고 가벼운 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "깔끔하고 청량한 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/10/30/6901035603010_1.png"
      },
      {
        name: "페로니 나스트로 아주로",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "이탈리아",
        alcohol: 5.1,
        rating: 4.4,
        description: "이탈리아의 유명한 라거 맥주로, 신선하고 시원한 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "상쾌하고 신선한 맛",
        image: "https://sc04.alicdn.com/kf/A6220a0c54dba44b7905ca6d1425f5d7bM.jpeg"
      },
      {
        name: "레페 브라운",
        type: "에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 6.5,
        rating: 4.6,
        description: "벨기에의 전통 에일 맥주로, 깊고 진한 맛과 캐러멜 풍미가 특징입니다.",
        price: 5000,
        tasteDescription: "깊고 진한 캐러멜 맛",
        image: "https://stage-cdn.veluga.kr/files/supplier/103/package_variation/3638.png"
      },
      {
        name: "필스너 우르켈",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "체코",
        alcohol: 4.4,
        rating: 4.5,
        description: "세계 최초의 필스너 맥주로, 풍부한 향과 쓴맛이 조화를 이룹니다.",
        price: 4500,
        tasteDescription: "깔끔한 홉의 쓴맛과 시원함",
        image: "https://t1.daumcdn.net/thumb/R720x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/6Eco/image/ZggWTCWAXmWOzG4ys4zLQsoI0Gc.jpg"
      },
      {
        name: "크로넨버그 1664 블랑",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "프랑스",
        alcohol: 5,
        rating: 4.5,
        description: "프랑스의 대표적인 밀맥주로, 상큼한 감귤 향과 부드러운 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "상큼한 감귤과 부드러운 밀 맛",
        image: "https://img1.daumcdn.net/thumb/R750x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99A0D133598867A70A"
      },
      {
        name: "삿포로 블랙",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5,
        rating: 4.4,
        description: "일본의 진한 스타우트 맥주로, 몰트의 깊은 맛과 크리미한 질감이 특징입니다.",
        price: 4500,
        tasteDescription: "진하고 깊은 몰트 맛",
        image: "https://www.sapporobeer.com/sites/default/files/styles/large/public/2023-10/product-page-can.png?itok=AhdeRNLf"
      },
      {
        name: "듀벨",
        type: "트리펠",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 8.5,
        rating: 4.7,
        description: "벨기에의 유명한 트리펠 맥주로, 강렬한 홉과 과일 향이 조화를 이룹니다.",
        price: 7000,
        tasteDescription: "강렬한 홉과 과일 향",
        image: "https://example.com/duvel.jpg"
      },
      {
        name: "사무엘 애덤스 보스턴 라거",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5,
        rating: 4.5,
        description: "미국의 프리미엄 라거로, 깊고 복합적인 몰트 풍미가 특징입니다.",
        price: 5500,
        tasteDescription: "복합적인 몰트와 홉의 조화",
        image: "https://example.com/samuel_adams.jpg"
      },
      {
        name: "하이네켄 다크",
        type: "다크 라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "네덜란드",
        alcohol: 5.5,
        rating: 4.3,
        description: "하이네켄의 다크 버전으로, 진하고 풍부한 몰트 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "진하고 깊은 몰트 맛",
        image: "https://example.com/heineken_dark.jpg"
      },
      {
        name: "모렐로 체리 비어",
        type: "과일 맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 3.5,
        rating: 4.6,
        description: "체리 향이 가득한 벨기에의 과일 맥주로, 달콤하면서도 상큼한 맛이 특징입니다.",
        price: 4500,
        tasteDescription: "달콤한 체리와 상큼한 맛",
        image: "https://example.com/morello_cherry.jpg"
      },
      {
        name: "밀러 라이트",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 4.2,
        rating: 4.0,
        description: "미국에서 사랑받는 저칼로리 라거 맥주로, 가볍고 청량한 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "가볍고 청량한 맛",
        image: "https://example.com/miller_light.jpg"
      },
      {
        name: "에스트렐라 담",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "스페인",
        alcohol: 5.4,
        rating: 4.3,
        description: "스페인의 대표 맥주로, 신선하고 깔끔한 풍미가 특징입니다.",
        price: 3500,
        tasteDescription: "신선하고 깔끔한 맛",
        image: "https://example.com/estrella_damm.jpg"
      },
      {
        name: "보헤미아",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "멕시코",
        alcohol: 4.7,
        rating: 4.2,
        description: "멕시코의 고급 필스너로, 쌉쌀한 홉의 풍미와 상쾌한 맛이 특징입니다.",
        price: 3200,
        tasteDescription: "쌉쌀하고 상쾌한 맛",
        image: "https://example.com/bohemia.jpg"
      },
      {
        name: "칭따오 스타우트",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "중국",
        alcohol: 5.3,
        rating: 4.2,
        description: "칭따오의 다크 버전 맥주로, 진하고 달콤한 몰트 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "진하고 달콤한 몰트 맛",
        image: "https://example.com/tsingtao_stout.jpg"
      },
      {
        name: "부드바르",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "체코",
        alcohol: 5,
        rating: 4.5,
        description: "체코의 전통적인 필스너 맥주로, 풍부한 홉의 향과 시원한 맛이 특징입니다.",
        price: 4500,
        tasteDescription: "풍부한 홉 향과 시원한 맛",
        image: "https://example.com/budvar.jpg"
      },
      {
        name: "타이거 맥주",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "싱가포르",
        alcohol: 5,
        rating: 4.1,
        description: "싱가포르에서 유명한 맥주로, 부드럽고 상쾌한 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "부드럽고 상쾌한 맛",
        image: "https://example.com/tiger_beer.jpg"
      },
      {
        name: "롤링 락",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 4.4,
        rating: 4.0,
        description: "미국에서 오랜 역사를 자랑하는 맥주로, 경쾌하고 청량한 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "경쾌하고 청량한 맛",
        image: "https://example.com/rolling_rock.jpg"
      },
      {
        name: "스텔라 아르투아",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 5.2,
        rating: 4.4,
        description: "벨기에의 고급 필스너 맥주로, 청량하고 우아한 홉의 향이 특징입니다.",
        price: 5000,
        tasteDescription: "청량하고 우아한 홉 향",
        image: "https://example.com/stella_artois.jpg"
      },
      {
        name: "발리틱 포터",
        type: "포터",
        category: "양조주",
        subCategory: "맥주",
        origin: "러시아",
        alcohol: 7.6,
        rating: 4.6,
        description: "러시아의 다크 포터 맥주로, 진하고 복합적인 몰트와 커피 향이 특징입니다.",
        price: 6000,
        tasteDescription: "진한 몰트와 커피 향",
        image: "https://example.com/baltic_porter.jpg"
      },
      {
        name: "미켈러 비어 긱 브렉퍼스트",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "덴마크",
        alcohol: 7.5,
        rating: 4.8,
        description: "덴마크의 프리미엄 스타우트로, 깊은 몰트와 다크 초콜릿 향이 조화를 이룹니다.",
        price: 7000,
        tasteDescription: "깊은 몰트와 다크 초콜릿 향",
        image: "https://example.com/mikkeller_beer_geek_breakfast.jpg"
      },
      {
        name: "에딩거 바이스비어",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "독일",
        alcohol: 5.3,
        rating: 4.5,
        description: "독일의 대표적인 밀맥주로, 부드럽고 상쾌한 맛이 특징입니다.",
        price: 4500,
        tasteDescription: "부드럽고 상쾌한 밀 향",
        image: "https://example.com/erdinger_weissbier.jpg"
      },
      {
        name: "파울라너 헤페바이스비어",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "독일",
        alcohol: 5.5,
        rating: 4.6,
        description: "바이에른 지역의 유명한 밀맥주로, 바나나와 정향의 향이 특징입니다.",
        price: 5000,
        tasteDescription: "바나나와 정향의 풍미",
        image: "https://example.com/paulaner_hefeweizen.jpg"
      },
      {
        name: "삿포로 클래식",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5.0,
        rating: 4.3,
        description: "삿포로의 클래식한 라거 맥주로, 청량하고 깔끔한 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "청량하고 깔끔한 맛",
        image: "https://example.com/sapporo_classic.jpg"
      },
      {
        name: "호가든 로제",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 3.0,
        rating: 4.4,
        description: "호가든의 과일 맥주 버전으로, 상큼한 라즈베리 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "상큼한 라즈베리 향",
        image: "https://example.com/hoegaarden_rose.jpg"
      },
      {
        name: "쿼크위노",
        type: "사워 에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "이탈리아",
        alcohol: 6.0,
        rating: 4.2,
        description: "이탈리아의 사워 에일 맥주로, 신선한 사과와 과일 향이 특징입니다.",
        price: 5500,
        tasteDescription: "신선한 사과와 과일 향",
        image: "https://example.com/querquino_sour_ale.jpg"
      },
      {
        name: "코젤 다크",
        type: "다크 라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "체코",
        alcohol: 3.8,
        rating: 4.5,
        description: "체코의 다크 라거로, 달콤한 몰트와 진한 초콜릿 향이 특징입니다.",
        price: 4000,
        tasteDescription: "달콤한 몰트와 초콜릿 향",
        image: "https://example.com/kozel_dark.jpg"
      },
      {
        name: "릭서즈 오렌지 비어",
        type: "과일 맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 3.5,
        rating: 4.1,
        description: "벨기에의 과일 맥주로, 상큼한 오렌지 향과 달콤한 맛이 특징입니다.",
        price: 4500,
        tasteDescription: "상큼한 오렌지와 달콤한 맛",
        image: "https://example.com/rixers_orange_beer.jpg"
      },
      {
        name: "킹피셔 라거",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "인도",
        alcohol: 4.8,
        rating: 4.0,
        description: "인도의 대표 라거 맥주로, 청량하고 시원한 맛이 특징입니다.",
        price: 3200,
        tasteDescription: "시원하고 청량한 맛",
        image: "https://example.com/kingfisher_lager.jpg"
      },
      {
        name: "발티카 넘버 7",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "러시아",
        alcohol: 5.4,
        rating: 4.2,
        description: "러시아의 인기 맥주로, 신선하고 쌉싸름한 홉 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "신선한 홉과 쌉싸름한 맛",
        image: "https://example.com/baltika_no7.jpg"
      },
      {
        name: "브룩클린 라거",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5.2,
        rating: 4.3,
        description: "미국 브루클린 지역에서 생산되는 라거 맥주로, 몰트의 깊은 풍미가 특징입니다.",
        price: 4500,
        tasteDescription: "깊은 몰트 풍미",
        image: "https://example.com/brooklyn_lager.jpg"
      },
      {
        name: "히타치노 네스트 화이트 에일",
        type: "에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5.5,
        rating: 4.5,
        description: "일본의 크래프트 맥주로, 상쾌한 감귤류와 향신료의 향이 특징입니다.",
        price: 5500,
        tasteDescription: "감귤류와 부드러운 향신료의 조화",
        image: "https://example.com/hitachino_nest_white_ale.jpg"
      },
      {
        name: "듀체스 드 부르고뉴",
        type: "사워 에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 6.2,
        rating: 4.7,
        description: "벨기에의 사워 에일로, 산미와 달콤한 캐러멜 향이 어우러진 맥주입니다.",
        price: 7000,
        tasteDescription: "산미와 캐러멜의 복합적인 맛",
        image: "https://example.com/duchesse_de_bourgogne.jpg"
      },
      {
        name: "듀벨 트리펠 홉",
        type: "트리펠",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 9.5,
        rating: 4.6,
        description: "벨기에의 유명한 듀벨 맥주에 더해진 홉의 강렬한 향과 높은 도수가 특징입니다.",
        price: 7500,
        tasteDescription: "강렬한 홉과 복합적인 풍미",
        image: "https://example.com/duvel_tripel_hop.jpg"
      },
      {
        name: "포터하우스 레드 에일",
        type: "레드 에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "아일랜드",
        alcohol: 4.4,
        rating: 4.2,
        description: "아일랜드의 전통적인 레드 에일로, 진한 몰트와 캐러멜 향이 특징입니다.",
        price: 4000,
        tasteDescription: "몰트와 캐러멜의 부드러운 조화",
        image: "https://example.com/porterhouse_red_ale.jpg"
      },
      {
        name: "하프 브라우 헤페바이스",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "독일",
        alcohol: 5.1,
        rating: 4.4,
        description: "독일 뮌헨에서 생산된 밀맥주로, 부드러운 바나나와 밀 향이 특징입니다.",
        price: 4800,
        tasteDescription: "부드러운 바나나와 밀 향",
        image: "https://example.com/hofbrau_hefeweizen.jpg"
      },
      {
        name: "투올 시티 광야 IPA",
        type: "IPA",
        category: "양조주",
        subCategory: "맥주",
        origin: "덴마크",
        alcohol: 6.5,
        rating: 4.5,
        description: "덴마크의 유명한 크래프트 브루어리에서 만들어진 IPA로, 시트러스와 꽃 향이 조화를 이룹니다.",
        price: 6000,
        tasteDescription: "시트러스와 꽃 향의 조화",
        image: "https://example.com/to_ol_city_safari_ipa.jpg"
      },
      {
        name: "발라딘 이삭",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "이탈리아",
        alcohol: 5.0,
        rating: 4.3,
        description: "이탈리아의 고급 밀맥주로, 오렌지와 향신료의 복합적인 향이 특징입니다.",
        price: 5500,
        tasteDescription: "오렌지와 향신료의 복합적인 풍미",
        image: "https://example.com/baladin_isaac.jpg"
      },
      {
        name: "골든 드락 9000 쿼드루펠",
        type: "쿼드루펠",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 10.5,
        rating: 4.8,
        description: "벨기에의 강렬한 쿼드루펠로, 진한 과일 향과 깊은 몰트 맛이 특징입니다.",
        price: 8000,
        tasteDescription: "깊은 몰트와 진한 과일 향",
        image: "https://example.com/gulden_draak_9000_quadruple.jpg"
      },
      {
        name: "옴미강 세종 해니페",
        type: "세종",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 7.7,
        rating: 4.6,
        description: "미국의 크래프트 맥주로, 상쾌한 과일 향과 달콤한 여운이 특징인 세종 스타일입니다.",
        price: 6500,
        tasteDescription: "상쾌한 과일과 달콤한 여운",
        image: "https://example.com/ommegang_hennepin_saison.jpg"
      },
      {
        name: "스톡홀름 브루어리 IPA",
        type: "IPA",
        category: "양조주",
        subCategory: "맥주",
        origin: "스웨덴",
        alcohol: 6.0,
        rating: 4.3,
        description: "스웨덴의 IPA로, 자몽과 파인애플의 상큼한 향과 쌉쌀한 홉 맛이 특징입니다.",
        price: 6000,
        tasteDescription: "자몽과 파인애플의 상큼함",
        image: "https://example.com/stockholm_brewery_ipa.jpg"
      },
      //증류주 50개(이제10개 넣음)
      {
        name: "글렌피딕 12년산",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.5,
        description: "신선한 사과와 배, 바닐라와 오크의 미묘한 맛이 조화를 이룹니다.",
        price: 70000,
        tasteDescription: "사과와 배, 바닐라, 오크",
        image: "https://cafe24.poxo.com/ec01/yms2310/HOvhRhvOk+Cp2KY4JuusAkTsbIYINUK2VSIGmcb5x6rWbiVFKFLJiOWiKTlmhPfGrqEqVOht/QNAz2W0Hrz3hg==/_/web/product/big/20200505/dee6086e60ca279582edfc8187d8831c.jpg"
      },
      {
        name: "조니 워커 블루 라벨",
        type: "블렌디드 스카치",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.9,
        description: "풍부하고 복합적인 맛, 부드러운 마무리가 특징인 프리미엄 블렌디드 위스키.",
        price: 230000,
        tasteDescription: "풍부한 과일, 스모키, 바닐라",
        image: "https://example.com/johnnie_walker_blue_label.jpg"
      },
      {
        name: "라프로익 10년산",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.7,
        description: "강렬한 피트 향과 바다의 염분이 조화를 이룬 독특한 맛이 특징입니다.",
        price: 85000,
        tasteDescription: "피트, 바다 염분, 바닐라",
        image: "https://example.com/laphroaig_10.jpg"
      },
      {
        name: "발베니 더블우드 12년산",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.6,
        description: "오크통과 쉐리통 숙성의 복합적인 풍미가 특징인 싱글 몰트 위스키.",
        price: 100000,
        tasteDescription: "오크, 쉐리, 말린 과일",
        image: "https://example.com/balvenie_doublewood_12.jpg"
      },
      {
        name: "맥캘란 12년 더블 캐스크",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.8,
        description: "미국산 오크통과 유럽산 오크통에서 숙성된 부드럽고 달콤한 위스키.",
        price: 120000,
        tasteDescription: "꿀, 시트러스, 오크",
        image: "https://example.com/macallan_double_cask_12.jpg"
      },
      {
        name: "잭 다니엘스 테네시 위스키",
        type: "테네시 위스키",
        category: "증류주",
        subCategory: "위스키",
        origin: "미국",
        alcohol: 40,
        rating: 4.5,
        description: "부드러운 스모키한 맛과 달콤한 캐러멜 향이 조화를 이루는 테네시 위스키.",
        price: 40000,
        tasteDescription: "스모키, 캐러멜, 바닐라",
        image: "https://example.com/jack_daniels.jpg"
      },
      {
        name: "카발란 솔리스트 셰리 캐스크",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "대만",
        alcohol: 58.6,
        rating: 4.7,
        description: "대만의 대표적인 싱글 몰트 위스키로, 진한 셰리 향과 몰트의 깊은 맛이 특징입니다.",
        price: 250000,
        tasteDescription: "셰리, 말린 과일, 초콜릿",
        image: "https://example.com/kavalan_sherry_cask.jpg"
      },
      {
        name: "바카디 골드 럼",
        type: "럼",
        category: "증류주",
        subCategory: "럼",
        origin: "푸에르토리코",
        alcohol: 40,
        rating: 4.3,
        description: "달콤한 바닐라와 오크 향이 가미된 부드러운 럼, 칵테일 베이스로 좋습니다.",
        price: 30000,
        tasteDescription: "바닐라, 오크, 토피",
        image: "https://example.com/bacardi_gold_rum.jpg"
      },
      {
        name: "앱솔루트 보드카",
        type: "보드카",
        category: "증류주",
        subCategory: "보드카",
        origin: "스웨덴",
        alcohol: 40,
        rating: 4.4,
        description: "깨끗하고 부드러운 맛이 특징인 스웨덴의 대표적인 보드카.",
        price: 25000,
        tasteDescription: "깨끗한 맛, 약간의 곡물 향",
        image: "https://example.com/absolut_vodka.jpg"
      },
      {
        name: "패트론 실버 테킬라",
        type: "테킬라",
        category: "증류주",
        subCategory: "테킬라",
        origin: "멕시코",
        alcohol: 40,
        rating: 4.6,
        description: "멕시코의 대표적인 고급 테킬라로, 깔끔하고 상쾌한 아가베 맛이 특징입니다.",
        price: 60000,
        tasteDescription: "아가베, 시트러스, 허브",
        image: "https://example.com/patron_silver_tequila.jpg"
      },
      //혼성주 50개(46개 넣어야함.)
      {
        name: "모히또",
        type: "칵테일",
        category: "혼성주",
        subCategory: "칵테일",
        origin: "쿠바",
        alcohol: 13,
        rating: 4.7,
        description: "민트와 라임, 설탕의 조화로 시원하고 상쾌한 맛.",
        price: 12000,
        tasteDescription: "민트와 라임의 상쾌함",
        image: "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA3MTVfODgg%2FMDAxNjI2MzMyMTg4Njg2.0LiDNhcV3W4uv2UKF0_kHmP6SyQabowEUBlcWU-IqXog.JlKWIC-VljAyrfD4erXMBuX3JgoFnFdyByhEEhgf9HQg.PNG.golmok_salon02%2Fimage.png&type=sc960_832"
      },
      {
        name: "다이퀴리",
        type: "칵테일",
        category: "혼성주",
        subCategory: "칵테일",
        origin: "쿠바",
        alcohol: 15,
        rating: 4.5,
        description: "라임 주스와 설탕이 더해진 럼 기반의 칵테일.",
        price: 15000,
        tasteDescription: "상큼한 라임과 달콤함",
        image: "https://i.namu.wiki/i/UnGhC8V5N3ycEpjmOP1ABm-pfx-lIiD_zvyxgHg-BpBSe0EBiciA3EdF1ocszy-Cx5IkQ3nwFg-wYtdN_Vudsw.webp"
      },
      {
        name: "니카 블랙 하이볼",
        type: "하이볼",
        category: "혼성주",
        subCategory: "하이볼",
        origin: "일본",
        alcohol: 9,
        rating: 4.4,
        description: "진한 몰트 맛과 상쾌한 진저의 조화.",
        price: 11000,
        tasteDescription: "몰트와 진저의 상쾌함",
        image: "https://mblogthumb-phinf.pstatic.net/MjAyNDA1MzBfMjg0/MDAxNzE3MDczNjE4NDAy.xAV366SefjwBF6F3SlAWcOY0gp6pg_TtNUJTfr3-AFMg.Sq0x4uPCUPzMasc7yKUv58MahxS_B2MlDIc3FBUR4gQg.JPEG/SE-37d2fc86-9990-4e2e-b573-f44ede37e198.jpg?type=w800"
      },
      {
        name: "산토리 가쿠빈 하이볼",
        type: "하이볼",
        category: "혼성주",
        subCategory: "하이볼",
        origin: "일본",
        alcohol: 10,
        rating: 4.5,
        description: "청량한 탄산과 부드러운 위스키 맛의 조화.",
        price: 10000,
        tasteDescription: "탄산과 위스키의 청량함",
        image: "https://cafe24.poxo.com/ec01/yms2310/HOvhRhvOk+Cp2KY4JuusAkTsbIYINUK2VSIGmcb5x6rWbiVFKFLJiOWiKTlmhPfGrqEqVOht/QNAz2W0Hrz3hg==/_/web/product/big/20191123/1d0cb3877d527ee5fd045e772a98bf78.jpg"
      },
      //전통주(아직 하나도 없음)
    ];
  }
  