function getDrinkData() {
    return [
      //양조주 50개
      {
        name: "버드와이저",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5,
        rating: 4.1,
        description: "세계적으로 유명한 맥주로, 가벼운 탄산과 부드러운 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "부드럽고 시원한 맛",
        image: "https://i3n.news1.kr/system/photos/2021/1/15/4576974/high.jpg"
      },
      {
        name: "하이네켄",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "네덜란드",
        alcohol: 5,
        rating: 4.2,
        description: "네덜란드의 대표적인 맥주로, 깔끔하고 상쾌한 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "깔끔하고 청량한 맛",
        image: "https://i.pinimg.com/564x/13/e1/3e/13e13ed8e5e93bbe19f93b87bfe2c61c.jpg"
      },
      {
        name: "아사히 슈퍼 드라이",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5,
        rating: 4.3,
        description: "일본의 대표 맥주로, 깔끔하고 청량한 드라이한 맛이 특징입니다.",
        price: 3200,
        tasteDescription: "드라이하고 깔끔한 맛",
        image: "https://cdn.veluga.kr/files/supplier/287/drinks/7.%E1%84%8C%E1%85%AE%E1%84%85%E1%85%A9%E1%86%BA%E1%84%83%E1%85%A6%E1%84%8B%E1%85%A1%E1%84%89%E1%85%A1%E1%84%92%E1%85%B5%E1%84%8C%E1%85%AE%E1%84%85%E1%85%B2_%E1%84%8B%E1%85%A1%E1%84%89%E1%85%A1%E1%84%92%E1%85%B5_%E1%84%89%E1%85%AE%E1%84%91%E1%85%A5_%E1%84%83%E1%85%B3%E1%84%85%E1%85%A1%E1%84%8B%E1%85%B5.png"
      },
      {
        name: "호가든",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 4.9,
        rating: 4.6,
        description: "벨기에의 대표적인 밀맥주로, 부드럽고 상쾌한 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "부드럽고 상쾌한 밀 맛",
        image: "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyNDA3MDJfOTgg%2FMDAxNzE5OTA4NDE5MDMy.lCPq2NcgELINpyc4iHxlKRz_R_a2XQngcpkUVz2MuFMg.BQxMyc1p0i96k19fv-LfhhWz1zqmMEf_SzWBzIVUfhkg.JPEG%2FIMG_0177.jpg&type=sc960_832"
      },
      {
        name: "기네스",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "아일랜드",
        alcohol: 4.2,
        rating: 4.8,
        description: "진한 색상과 부드러운 크림 거품, 깊고 진한 맛이 특징인 맥주입니다.",
        price: 5000,
        tasteDescription: "깊고 진한 몰트 맛",
        image: "https://cdn.imweb.me/thumbnail/20201222/9be70d4e2232b.jpg"
      },
      {
        name: "카스 프레시",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "대한민국",
        alcohol: 4.5,
        rating: 4.0,
        description: "한국에서 가장 인기 있는 라거 맥주로, 시원하고 청량한 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "시원하고 청량한 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/24/10/8801858011024_1.png"
      },
      {
        name: "테라",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "대한민국",
        alcohol: 4.6,
        rating: 4.2,
        description: "청정 라거로 유명한 테라는 부드럽고 깔끔한 맛을 제공합니다.",
        price: 3200,
        tasteDescription: "부드럽고 깔끔한 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/11/00/8801119770011_1.png"
      },
      {
        name: "산 미구엘",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "필리핀",
        alcohol: 5,
        rating: 4.1,
        description: "필리핀에서 가장 인기 있는 맥주로, 가벼운 맛과 청량감이 특징입니다.",
        price: 2800,
        tasteDescription: "청량하고 상쾌한 맛",
        image: "https://theliquor.net/wp-content/uploads/2020/06/pilsen-e1591228861468.png"
      },
      {
        name: "코로나",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "멕시코",
        alcohol: 4.6,
        rating: 4.5,
        description: "라임과 함께 마시면 더욱 상쾌한 멕시코 대표 맥주입니다.",
        price: 4000,
        tasteDescription: "상쾌하고 가벼운 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/13/50/8801021215013_1.png"
      },
      {
        name: "블루문",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5.4,
        rating: 4.4,
        description: "미국의 인기 밀맥주로, 부드럽고 상큼한 오렌지 향이 특징입니다.",
        price: 4500,
        tasteDescription: "부드러운 밀과 상큼한 오렌지 향",
        image: "https://pimg.mk.co.kr/meet/neds/2018/06/image_readtop_2018_380078_15290964623352759.jpg"
      },
      {
        name: "칭따오",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "중국",
        alcohol: 4.7,
        rating: 4.3,
        description: "중국의 대표 맥주로, 깔끔하고 가벼운 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "깔끔하고 청량한 맛",
        image: "https://images.emarteveryday.co.kr/images/app/webapps/evd_web2/share/SKU/mall/10/30/6901035603010_1.png"
      },
      {
        name: "페로니 나스트로 아주로",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "이탈리아",
        alcohol: 5.1,
        rating: 4.4,
        description: "이탈리아의 유명한 라거 맥주로, 신선하고 시원한 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "상쾌하고 신선한 맛",
        image: "https://sc04.alicdn.com/kf/A6220a0c54dba44b7905ca6d1425f5d7bM.jpeg"
      },
      {
        name: "레페 브라운",
        type: "에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 6.5,
        rating: 4.6,
        description: "벨기에의 전통 에일 맥주로, 깊고 진한 맛과 캐러멜 풍미가 특징입니다.",
        price: 5000,
        tasteDescription: "깊고 진한 캐러멜 맛",
        image: "https://stage-cdn.veluga.kr/files/supplier/103/package_variation/3638.png"
      },
      {
        name: "필스너 우르켈",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "체코",
        alcohol: 4.4,
        rating: 4.5,
        description: "세계 최초의 필스너 맥주로, 풍부한 향과 쓴맛이 조화를 이룹니다.",
        price: 4500,
        tasteDescription: "깔끔한 홉의 쓴맛과 시원함",
        image: "https://t1.daumcdn.net/thumb/R720x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/6Eco/image/ZggWTCWAXmWOzG4ys4zLQsoI0Gc.jpg"
      },
      {
        name: "크로넨버그 1664 블랑",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "프랑스",
        alcohol: 5,
        rating: 4.5,
        description: "프랑스의 대표적인 밀맥주로, 상큼한 감귤 향과 부드러운 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "상큼한 감귤과 부드러운 밀 맛",
        image: "https://img1.daumcdn.net/thumb/R750x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99A0D133598867A70A"
      },
      {
        name: "삿포로 블랙",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5,
        rating: 4.4,
        description: "일본의 진한 스타우트 맥주로, 몰트의 깊은 맛과 크리미한 질감이 특징입니다.",
        price: 4500,
        tasteDescription: "진하고 깊은 몰트 맛",
        image: "https://www.sapporobeer.com/sites/default/files/styles/large/public/2023-10/product-page-can.png?itok=AhdeRNLf"
      },
      {
        name: "듀벨",
        type: "트리펠",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 8.5,
        rating: 4.7,
        description: "벨기에의 유명한 트리펠 맥주로, 강렬한 홉과 과일 향이 조화를 이룹니다.",
        price: 7000,
        tasteDescription: "강렬한 홉과 과일 향",
        image: "https://i.namu.wiki/i/ehTSsCNpPASKCwtjCmSCnqTdYO2aA4Mdy9p__lJaVEulZQXaP1vPnzJMk3HmTne-PrwSHujQfl73PDr6V9kD0A.webp"
      },
      {
        name: "사무엘 애덤스 보스턴 라거",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5,
        rating: 4.5,
        description: "미국의 프리미엄 라거로, 깊고 복합적인 몰트 풍미가 특징입니다.",
        price: 5500,
        tasteDescription: "복합적인 몰트와 홉의 조화",
        image: "https://cdn.veluga.kr/drinks/0/main/407ce4efbfd747ac918f0ef26a908196_2.png"
      },
      {
        name: "하이네켄 다크",
        type: "다크 라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "네덜란드",
        alcohol: 5.5,
        rating: 4.3,
        description: "하이네켄의 다크 버전으로, 진하고 풍부한 몰트 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "진하고 깊은 몰트 맛",
        image: "https://cdn.veluga.kr/drinks/0/main/1fccd9ebe283479599bd4d02170b1dc6_%ED%95%98%EC%9D%B4%EB%84%A4%EC%BC%84_%EB%8B%A4%ED%81%AC%EB%9D%BC%EA%B1%B0.png"
      },
      {
        name: "프루이 스트로베리 비어",
        type: "과일 맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 4.1,
        rating: 4.7,
        description: "벨기에의 대표적인 딸기 과일 맥주로, 신선한 딸기 향과 달콤한 맛이 특징입니다.",
        price: 5000,
        tasteDescription: "달콤한 딸기와 신선한 과일 향",
        image: "https://cdn.imweb.me/thumbnail/20220713/112d469bf39e2.png"
      },    
      {
        name: "밀러 라이트",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 4.2,
        rating: 4.0,
        description: "미국에서 사랑받는 저칼로리 라거 맥주로, 가볍고 청량한 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "가볍고 청량한 맛",
        image: "https://lh6.googleusercontent.com/proxy/zs6QFiPX-K9Feysv2VMdcy1pog_ik4eM3xGU569LABSZ3DllYAqxU4X7igl2H5JzeP_IY89CzToFHXd_TUD4f-5tDpWEr_p6wdnRftGRp8qOblbNZF6mNQL4Vco-7fdhWTmLRhh_UMlU-z9BSW8HvZQ6tcU"
      },
      {
        name: "에스트렐라 담",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "스페인",
        alcohol: 5.4,
        rating: 4.3,
        description: "스페인의 대표 맥주로, 신선하고 깔끔한 풍미가 특징입니다.",
        price: 3500,
        tasteDescription: "신선하고 깔끔한 맛",
        image: "https://www.dranken.co.uk/cdn/shop/products/estrelladamm330ml.jpg?v=1623335670"
      },
      {
        name: "보헤미아",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "멕시코",
        alcohol: 4.7,
        rating: 4.2,
        description: "멕시코의 고급 필스너로, 쌉쌀한 홉의 풍미와 상쾌한 맛이 특징입니다.",
        price: 3200,
        tasteDescription: "쌉쌀하고 상쾌한 맛",
        image: "https://arizona.bevmo.com/cdn/shop/files/8a56346f-318f-47c4-9e2b-79b2e153b72c_f353b77b-5844-4779-aea0-a251a518680c.png?v=1718249447&width=1445"
      },
      {
        name: "칭따오 스타우트",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "중국",
        alcohol: 5.3,
        rating: 4.2,
        description: "칭따오의 다크 버전 맥주로, 진하고 달콤한 몰트 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "진하고 달콤한 몰트 맛",
        image: "https://stage-cdn.veluga.kr/files/supplier/104/package_variation/3493.png"
      },
      {
        name: "부드바르",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "체코",
        alcohol: 5,
        rating: 4.5,
        description: "체코의 전통적인 필스너 맥주로, 풍부한 홉의 향과 시원한 맛이 특징입니다.",
        price: 4500,
        tasteDescription: "풍부한 홉 향과 시원한 맛",
        image: "https://i.namu.wiki/i/Lh1VaGyanc_aDokcFjw0f1DJlyegMkTDXJ7YDAcXbca8MYK8anqXDLQUPR3aR97_1VSGXRcUU2Jjsu83vH1heQ.webp"
      },
      {
        name: "타이거 맥주",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "싱가포르",
        alcohol: 5,
        rating: 4.1,
        description: "싱가포르에서 유명한 맥주로, 부드럽고 상쾌한 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "부드럽고 상쾌한 맛",
        image: "https://cdn.imweb.me/thumbnail/20201220/e8eee448283ca.jpeg"
      },
      {
        name: "롤링 락",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 4.4,
        rating: 4.0,
        description: "미국에서 오랜 역사를 자랑하는 맥주로, 경쾌하고 청량한 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "경쾌하고 청량한 맛",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzqA9fUt8abkVPIYhiJDOXQzcJa6BECTj2WQ&s"
      },
      {
        name: "스텔라 아르투아",
        type: "필스너",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 5.2,
        rating: 4.4,
        description: "벨기에의 고급 필스너 맥주로, 청량하고 우아한 홉의 향이 특징입니다.",
        price: 5000,
        tasteDescription: "청량하고 우아한 홉 향",
        image: "https://i.namu.wiki/i/yBOP0PWcyhbJklMV8aRmu5sLu5kxwdkvSl2uEHWs5H20BHPlv7gD4kumc6YgMTv7sTPXgNuofe0O69c7YdJ6JQ.webp"
      },
      {
        name: "린데만스 크릭",
        type: "과일 맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 3.5,
        rating: 4.6,
        description: "벨기에 전통 체리 람빅 맥주로, 새콤달콤한 체리 향과 은은한 산미가 조화를 이루는 상쾌한 맛이 특징입니다.",
        price: 5000,
        tasteDescription: "달콤한 체리와 상큼한 산미",
        image: "https://sklepimpuls.pl/wp-content/uploads/2022/02/Lindemans-Kriek.png"
      },     
      {
        name: "미켈러 비어 긱 브렉퍼스트",
        type: "스타우트",
        category: "양조주",
        subCategory: "맥주",
        origin: "덴마크",
        alcohol: 7.5,
        rating: 4.8,
        description: "덴마크의 프리미엄 스타우트로, 깊은 몰트와 다크 초콜릿 향이 조화를 이룹니다.",
        price: 7000,
        tasteDescription: "깊은 몰트와 다크 초콜릿 향",
        image: "https://beerlikeit.com/upimg/brd/BRD0002477.jpg"
      },
      {
        name: "에딩거 바이스비어",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "독일",
        alcohol: 5.3,
        rating: 4.5,
        description: "독일의 대표적인 밀맥주로, 부드럽고 상쾌한 맛이 특징입니다.",
        price: 4500,
        tasteDescription: "부드럽고 상쾌한 밀 향",
        image: "https://stage-cdn.veluga.kr/files/supplier/104/package_variation/3502.png"
      },
      {
        name: "파울라너 헤페바이스비어",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "독일",
        alcohol: 5.5,
        rating: 4.6,
        description: "바이에른 지역의 유명한 밀맥주로, 바나나와 정향의 향이 특징입니다.",
        price: 5000,
        tasteDescription: "바나나와 정향의 풍미",
        image: "https://cdn.imweb.me/thumbnail/20210111/5df173a0e6640.png"
      },
      {
        name: "삿포로 클래식",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5.0,
        rating: 4.3,
        description: "삿포로의 클래식한 라거 맥주로, 청량하고 깔끔한 맛이 특징입니다.",
        price: 3500,
        tasteDescription: "청량하고 깔끔한 맛",
        image: "https://www.sapporo.travel/cms/wp-content/uploads/2020/10/ph_091.jpg"
      },
      {
        name: "호가든 로제",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 3.0,
        rating: 4.4,
        description: "호가든의 과일 맥주 버전으로, 상큼한 라즈베리 맛이 특징입니다.",
        price: 4000,
        tasteDescription: "상큼한 라즈베리 향",
        image: "https://stage-cdn.veluga.kr/files/supplier/103/package_variation/3610.png"
      },
      {
        name: "페로니 나스트로 아주로",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "이탈리아",
        alcohol: 5.1,
        rating: 4.5,
        description: "이탈리아의 대표 라거 맥주로, 청량하고 깔끔한 맛이 특징입니다. 홉과 몰트의 균형이 잘 잡혀있어 가볍고 시원하게 즐길 수 있습니다.",
        price: 5000,
        tasteDescription: "상쾌한 청량감과 깔끔한 마무리",
        image: "https://sc04.alicdn.com/kf/A6220a0c54dba44b7905ca6d1425f5d7bM.jpeg"
      },
      {
        name: "코젤 다크",
        type: "다크 라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "체코",
        alcohol: 3.8,
        rating: 4.5,
        description: "체코의 다크 라거로, 달콤한 몰트와 진한 초콜릿 향이 특징입니다.",
        price: 4000,
        tasteDescription: "달콤한 몰트와 초콜릿 향",
        image: "https://cdn.imweb.me/thumbnail/20210105/a988a0d3e41cd.jpeg"
      },
      {
        name: "오르발",
        type: "트라피스트 에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 6.2,
        rating: 4.7,
        description: "벨기에 트라피스트 맥주로, 홉의 쌉쌀한 맛과 약간의 신맛이 조화롭게 어우러져 깊고 복합적인 풍미가 특징입니다.",
        price: 6000,
        tasteDescription: "홉의 쌉쌀함과 와인처럼 숙성된 풍미",
        image: "https://www.hmap.co.kr/upload/editor/1663685154_nYP_orval_beer.jpg"
      },    
      {
        name: "킹피셔 라거",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "인도",
        alcohol: 4.8,
        rating: 4.0,
        description: "인도의 대표 라거 맥주로, 청량하고 시원한 맛이 특징입니다.",
        price: 3200,
        tasteDescription: "시원하고 청량한 맛",
        image: "https://mcgrocer.com/cdn/shop/files/0ea9a6d60751bc6c8dc375dc2578e809_grande.jpg?v=1714224345"
      },
      {
        name: "발티카 넘버 7",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "러시아",
        alcohol: 5.4,
        rating: 4.2,
        description: "러시아의 인기 맥주로, 신선하고 쌉싸름한 홉 맛이 특징입니다.",
        price: 3000,
        tasteDescription: "신선한 홉과 쌉싸름한 맛",
        image: "https://image.mycelebs.com/beer/new/sq/241397_sq_00.jpg"
      },
      {
        name: "브루클린 라거",
        type: "라거",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 5.2,
        rating: 4.3,
        description: "미국 브루클린 지역에서 생산되는 라거 맥주로, 몰트의 깊은 풍미가 특징입니다.",
        price: 4500,
        tasteDescription: "깊은 몰트 풍미",
        image: "https://beerlikeit.com/upimg/brd/BRD0001751.png"
      },
      {
        name: "히타치노 네스트 화이트 에일",
        type: "에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "일본",
        alcohol: 5.5,
        rating: 4.5,
        description: "일본의 크래프트 맥주로, 상쾌한 감귤류와 향신료의 향이 특징입니다.",
        price: 5500,
        tasteDescription: "감귤류와 부드러운 향신료의 조화",
        image: "https://beerlikeit.com/upimg/brd/BRD0001148.png"
      },
      {
        name: "듀체스 드 부르고뉴",
        type: "사워 에일",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 6.2,
        rating: 4.7,
        description: "벨기에의 사워 에일로, 산미와 달콤한 캐러멜 향이 어우러진 맥주입니다.",
        price: 7000,
        tasteDescription: "산미와 캐러멜의 복합적인 맛",
        image: "https://beerlikeit.com/upimg/brd/imzwEgW5Ok0rIVARNGM27dLQKZjDwFXq.jpg"
      },
      {
        name: "듀벨 트리펠 홉",
        type: "트리펠",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 9.5,
        rating: 4.6,
        description: "벨기에의 유명한 듀벨 맥주에 더해진 홉의 강렬한 향과 높은 도수가 특징입니다.",
        price: 7500,
        tasteDescription: "강렬한 홉과 복합적인 풍미",
        image: "https://assets.business.veluga.kr/media/public/Duvel_Duvel_Tripel_Hop_Citra.png"
      },
      {
        "name": "스미딕스 레드 에일",
        "type": "레드 에일",
        "category": "양조주",
        "subCategory": "맥주",
        "origin": "아일랜드",
        "alcohol": 4.5,
        "rating": 4.3,
        "description": "아일랜드의 전통적인 레드 에일로, 부드러운 몰트와 캐러멜의 풍미가 조화롭게 어우러져 있습니다.",
        "price": 4500,
        "tasteDescription": "부드러운 몰트와 캐러멜의 풍미",
        "image": "https://img1.daumcdn.net/thumb/R1280x0/?fname=https://t1.daumcdn.net/brunch/service/user/7A3i/image/VmN7BFtUrTTwSL2rsdhe_h1rj2E.jpg"
      },    
      {
        name: "호프브로이 헤페바이스",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "독일",
        alcohol: 5.1,
        rating: 4.4,
        description: "독일 뮌헨에서 생산된 밀맥주로, 부드러운 바나나와 밀 향이 특징입니다.",
        price: 4800,
        tasteDescription: "부드러운 바나나와 밀 향",
        image: "https://cdn.imweb.me/thumbnail/20201220/b6f1e4b39ccdd.jpeg"
      },
      {
        name: "시티 세션 IPA",
        type: "IPA",
        category: "양조주",
        subCategory: "맥주",
        origin: "덴마크",
        alcohol: 6.5,
        rating: 4.5,
        description: "덴마크의 유명한 크래프트 브루어리에서 만들어진 IPA로, 시트러스와 꽃 향이 조화를 이룹니다.",
        price: 6000,
        tasteDescription: "시트러스와 꽃 향의 조화",
        image: "https://assets.business.veluga.kr/media/public/to_ol_City_Session_IPA_HXRjZTA.png"
      },
      {
        name: "발라딘 이삭",
        type: "밀맥주",
        category: "양조주",
        subCategory: "맥주",
        origin: "이탈리아",
        alcohol: 5.0,
        rating: 4.3,
        description: "이탈리아의 고급 밀맥주로, 오렌지와 향신료의 복합적인 향이 특징입니다.",
        price: 5500,
        tasteDescription: "오렌지와 향신료의 복합적인 풍미",
        image: "https://www.biraghiacasa.it/20495-large_default/birra-isaac-33cl.jpg"
      },
      {
        name: "골든 드락 9000 쿼드루펠",
        type: "쿼드루펠",
        category: "양조주",
        subCategory: "맥주",
        origin: "벨기에",
        alcohol: 10.5,
        rating: 4.8,
        description: "벨기에의 강렬한 쿼드루펠로, 진한 과일 향과 깊은 몰트 맛이 특징입니다.",
        price: 8000,
        tasteDescription: "깊은 몰트와 진한 과일 향",
        image: "https://stage-cdn.veluga.kr/files/supplier/23/package_variation/812.png"
      },
      {
        name: "옴미강 세종 해니페",
        type: "세종",
        category: "양조주",
        subCategory: "맥주",
        origin: "미국",
        alcohol: 7.7,
        rating: 4.6,
        description: "미국의 크래프트 맥주로, 상쾌한 과일 향과 달콤한 여운이 특징인 세종 스타일입니다.",
        price: 6500,
        tasteDescription: "상쾌한 과일과 달콤한 여운",
        image: "https://craftshack.com/cdn/shop/products/Ommegang-Hennepin-Farmhouse-Saison-Ale-12OZ-BTL.jpg?v=1668432653"
      },
      {
        name: "스톡홀름 브루어리 IPA",
        type: "IPA",
        category: "양조주",
        subCategory: "맥주",
        origin: "스웨덴",
        alcohol: 6.0,
        rating: 4.3,
        description: "스웨덴의 IPA로, 자몽과 파인애플의 상큼한 향과 쌉쌀한 홉 맛이 특징입니다.",
        price: 6000,
        tasteDescription: "자몽과 파인애플의 상큼함",
        image: "https://images.squarespace-cdn.com/content/v1/537d13cae4b0b522497e2f73/1604994823081-L1VA4GPMEEXM0MTISAST/stockholm+lager"
      },
      //양조주-와인 50개
      {
        "name": "샤또 마르고",
        "type": "레드 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "프랑스",
        "alcohol": 13.5,
        "rating": 4.8,
        "description": "프랑스의 대표적인 레드 와인으로, 풍부한 탄닌과 오크 향이 조화를 이루는 고급 와인입니다.",
        "price": 150000,
        "tasteDescription": "풍부한 탄닌과 오크 향",
        "image": "https://www.directwine.shop/cdn/shop/files/10033-Chateau-Margaux-O-800_0504db8a-6107-495c-a0c6-bdee0419e433.png?v=1711942484"
    },
    {
        "name": "페트루스",
        "type": "레드 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "프랑스",
        "alcohol": 14.0,
        "rating": 4.9,
        "description": "포도의 농축된 향과 진한 질감이 특징인 프랑스 최고급 와인 중 하나입니다.",
        "price": 300000,
        "tasteDescription": "농축된 포도 향과 진한 질감",
        "image": "https://awine.kr/wp-content/uploads/vb_wine_img/1751.png"
    },
    {
        "name": "캘리포니아 나파 까베르네 소비뇽",
        "type": "레드 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "미국",
        "alcohol": 14.5,
        "rating": 4.7,
        "description": "캘리포니아의 대표적인 까베르네 소비뇽으로, 체리와 블랙베리의 진한 맛이 매력적입니다.",
        "price": 85000,
        "tasteDescription": "체리와 블랙베리의 진한 맛",
        "image": "https://images.commerce7.com/napa-cellars/images/large/napc-v2021-cs-front-bottle-lr-1712246675012.png"
    },
    {
        "name": "바로사 밸리 쉬라즈",
        "type": "레드 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "호주",
        "alcohol": 14.8,
        "rating": 4.6,
        "description": "호주의 바로사 밸리에서 생산된 시라즈로, 스파이시한 향과 진한 과일 향이 특징입니다.",
        "price": 70000,
        "tasteDescription": "스파이시한 향과 진한 과일 향",
        "image": "https://d2ur3emorbx826.cloudfront.net/product/124111/thumbnail/%EB%B0%94%EB%A1%9C%EC%82%AC%20%EB%B0%B8%EB%A6%AC%20%ED%8C%9C%20%EC%89%AC%EB%9D%BC%EC%A6%88_20220513041357.png"
    },
    {
        "name": "지아콘디 산지오베제",
        "type": "레드 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "이탈리아",
        "alcohol": 13.0,
        "rating": 4.4,
        "description": "이탈리아의 대표적인 와인으로, 체리와 약간의 산미가 어우러진 레드 와인입니다.",
        "price": 50000,
        "tasteDescription": "체리와 산미의 조화",
        "image": "https://mondodelvino.co.kr/wp-content/uploads/2020/04/mgm-giocondi-sangiovese.jpg"
    },
    {
        "name": "모젤 크리스마스 리슬링",
        "type": "화이트 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "독일",
        "alcohol": 12.0,
        "rating": 4.5,
        "description": "독일 모젤 지역의 리슬링으로, 산뜻한 산미와 복숭아 향이 돋보이는 화이트 와인입니다.",
        "price": 40000,
        "tasteDescription": "산뜻한 산미와 복숭아 향",
        "image": "https://cafe24.poxo.com/ec01/letsdowine/fYw07Q+e08011Z5Qzbz30yC0JvqcXWvQcBdvn52sOz689E+Ww8NvS3kIz1BovuxPSD13RAqqxECLxwIolL8rLg==/_/web/product/big/202411/21a7093564c0cab738b4cde5ec0e09e0.jpg"
    },
    {
        "name": "샤블리 프리미에 크뤼",
        "type": "화이트 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "프랑스",
        "alcohol": 12.5,
        "rating": 4.6,
        "description": "프랑스 샤블리 지역에서 생산된 화이트 와인으로, 미네랄과 사과 향이 조화로운 와인입니다.",
        "price": 60000,
        "tasteDescription": "미네랄과 사과 향",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtSPA3CCHW6KPZQelT8bx8UlfmhDfxhSuizA&s"
    },
    {
        "name": "떼루뇨 까르미네르",
        "type": "레드 와인",
        "category": "양조주",
        "subCategory": "와인",
        "origin": "칠레",
        "alcohol": 13.5,
        "rating": 4.4,
        "description": "칠레에서 생산된 부드러운 질감과 베리 향이 특징인 레드 와인입니다.",
        "price": 45000,
        "tasteDescription": "부드러운 질감과 베리 향",
        "image": "https://lh5.googleusercontent.com/proxy/vFHEGqJ_j8hRvWp2zNay_1Jac0_rseN2ZHbhEM3_k7zaApbNEo0DT_N9_MnsDOcaN1S3vzhvhEprYwY8iqRqdSNmX0U8LJAa_5DVzaz0pSOL"
    },
    {
      "name": "조닌 소아베 클라시코",
      "type": "화이트 와인",
      "category": "양조주",
      "subCategory": "와인",
      "origin": "이탈리아",
      "alcohol": 11.5,
      "rating": 4.2,
      "description": "이탈리아 소아베 지역에서 조닌 와이너리가 생산한 화이트 와인으로, 은은한 꽃 향과 신선한 산미가 특징입니다.",
      "price": 35000,
      "tasteDescription": "은은한 꽃 향과 신선한 산미",
      "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/157.%E1%84%85%E1%85%A9%E1%86%BA%E1%84%83%E1%85%A6%E1%84%8E%E1%85%B5%E1%86%AF%E1%84%89%E1%85%A5%E1%86%BC_%E1%84%8C%E1%85%A9%E1%84%82%E1%85%B5%E1%86%AB_%E1%84%89%E1%85%A9%E1%84%8B%E1%85%A1%E1%84%87%E1%85%A6_%E1%84%8F%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A1%E1%84%89%E1%85%B5%E1%84%8F%E1%85%A9.png"
    },
    {
      "name": "클라우디 베이 소비뇽 블랑",
      "type": "화이트 와인",
      "category": "양조주",
      "subCategory": "와인",
      "origin": "뉴질랜드",
      "alcohol": 13.0,
      "rating": 4.8,
      "description": "뉴질랜드 말보로 지역에서 생산된 클라우디 베이의 소비뇽 블랑으로, 상큼한 열대 과일과 구아바 향이 돋보입니다.",
      "price": 75000,
      "tasteDescription": "열대 과일과 구아바의 향긋함",
      "image": "https://lh4.googleusercontent.com/proxy/fqa2ssAVW4ONT9Ympi49cLTltyZOdRB-zrnTKLJWdv2U_nzmHxD3GhyfmRH00BOuNiAP7oBWPNkJHhkilAfauPqZD04OLtrZlR5ZvrZd511s"
    },
    {
      "name": "샤또 라피트 로칠드",
      "type": "레드 와인",
      "category": "양조주",
      "subCategory": "와인",
      "origin": "프랑스",
      "alcohol": 13.0,
      "rating": 4.9,
      "description": "프랑스 보르도 지역의 최고급 와인으로, 깊은 탄닌과 오랜 숙성 잠재력을 지닌 와인입니다.",
      "price": 200000,
      "tasteDescription": "깊은 탄닌과 오랜 숙성의 풍미",
      "image": "https://www.directwine.shop/cdn/shop/files/10786-chateau-lafite-rothschild-h-790_80dd745d-67e4-4c19-8824-f2cc8c86a5b9.png?v=1685500362"
  },
  {
      "name": "도멘 드 라 로마네 콩티",
      "type": "레드 와인",
      "category": "양조주",
      "subCategory": "와인",
      "origin": "프랑스",
      "alcohol": 13.5,
      "rating": 5.0,
      "description": "부르고뉴의 전설적인 와인으로, 과일의 깊은 향과 우아한 탄닌이 조화를 이룹니다.",
      "price": 250000,
      "tasteDescription": "깊은 과일 향과 우아한 탄닌",
      "image": "https://www.directwine.shop/cdn/shop/files/10428-domaine-de-la-romanee-conti-romanee-saint-vivant-2015-O2-800_600x600_crop_center.png?v=1711003837"
  },
  {
    "name": "벨 꼴레 바롤로",
    "type": "레드 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "이탈리아",
    "alcohol": 14.0,
    "rating": 4.7,
    "description": "이탈리아 피에몬테 지역의 바롤로로, 깊고 풍부한 타닌과 체리, 자두 향이 인상적인 고급 레드 와인입니다.",
    "price": 90000,
    "tasteDescription": "깊고 풍부한 타닌과 체리, 자두의 복합적인 향",
    "image": "https://www.naracellar.com/img_wine/upload/big/3553575307_BfgoIEW3_64817adbdc444b4c7767b4389b206dbe00cd8fba.jpg"
  },
  {
    "name": "안티노리 틴타넬로",
    "type": "레드 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "이탈리아",
    "alcohol": 13.5,
    "rating": 4.7,
    "description": "이탈리아 토스카나 지역의 슈퍼 투스칸 와인으로, 잘 익은 체리와 스파이스 향이 복합적으로 어우러집니다.",
    "price": 120000,
    "tasteDescription": "체리와 스파이스의 복합적인 향",
    "image": "https://www.directwine.shop/cdn/shop/files/10447-Tignanello_Ver2-H-800_a6a531d7-c7a6-49df-ae35-06914d306e47.png?v=1711706868"
  },
  {
      "name": "오푸스 원",
      "type": "레드 와인",
      "category": "양조주",
      "subCategory": "와인",
      "origin": "미국",
      "alcohol": 14.5,
      "rating": 4.8,
      "description": "캘리포니아의 상징적인 와인으로, 블랙베리와 초콜릿의 진한 풍미를 자랑합니다.",
      "price": 180000,
      "tasteDescription": "블랙베리와 초콜릿의 진한 풍미",
      "image": "https://cdn.imweb.me/upload/S201805075af0125698fa0/ecfb22c16960b.png"
  },
  {
      "name": "루이 라뚜르 샤르도네",
      "type": "화이트 와인",
      "category": "양조주",
      "subCategory": "와인",
      "origin": "프랑스",
      "alcohol": 13.0,
      "rating": 4.4,
      "description": "프랑스 부르고뉴 지역의 샤르도네로, 미네랄리티와 사과, 배 향이 돋보이는 와인입니다.",
      "price": 55000,
      "tasteDescription": "사과와 배의 신선한 향",
      "image": "https://www.winenara.com/uploads/product/492_detail_079.png"
  },
  {
    "name": "루이 자도 샤블리",
    "type": "화이트 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "프랑스",
    "alcohol": 12.5,
    "rating": 4.8,
    "description": "프랑스 부르고뉴의 샤블리 지역에서 생산된 샤르도네로, 미네랄과 상쾌한 시트러스 향이 돋보이는 고급 와인입니다.",
    "price": 55000,
    "tasteDescription": "미네랄과 상쾌한 시트러스 풍미",
    "image": "https://www.shinsegae-lnb.com/upload/product/wine/wine/images/W_368_LouisJadotChablis1erCruFourchaume.jpg"
  },
  {
    "name": "폴렌바이더 심복 리슬링 트로켄",
    "type": "화이트 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "독일",
    "alcohol": 12.0,
    "rating": 4.7,
    "description": "독일 모젤 지역의 리슬링 와인으로, 산뜻한 산미와 섬세한 과일 향이 특징입니다.",
    "price": 35000,
    "tasteDescription": "산미와 섬세한 과일 향",
    "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/153._%E1%84%85%E1%85%A6%E1%84%87%E1%85%A2%E1%86%BC%E1%84%83%E1%85%B3%E1%84%86%E1%85%A2%E1%84%8B%E1%85%B5%E1%86%AF_%E1%84%91%E1%85%A9%E1%86%AF%E1%84%85%E1%85%A6%E1%86%AB%E1%84%87%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%83%E1%85%A5_%E1%84%89%E1%85%B5%E1%86%B7%E1%84%87%E1%85%A9%E1%86%A8_%E1%84%85%E1%85%B5%E1%84%89%E1%85%B3%E1%86%AF%E1%84%85%E1%85%B5%E1%86%BC_%E1%84%90%E1%85%B3%E1%84%85%E1%85%A9%E1%84%8F%E1%85%A6%E1%86%AB.png"
  },
  {
    "name": "콘차이토로 푸두 카베르네 소비뇽 쉬라즈",
    "type": "레드 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "칠레",
    "alcohol": 13.5,
    "rating": 4.4,
    "description": "칠레에서 생산된 카베르네 소비뇽과 쉬라즈가 블렌딩된 레드 와인으로, 깊은 과일 향과 스파이시한 풍미가 특징입니다.",
    "price": 30000,
    "tasteDescription": "깊은 과일 향과 스파이시한 풍미",
    "image": "https://www.winenara.com/uploads/product/550/a169d48868313f31cb8f5e8dff48658e.png"
  },
  {
    "name": "라 벨 앙젤르 피노 누아",
    "type": "레드 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "프랑스",
    "alcohol": 13.0,
    "rating": 4.4,
    "description": "프랑스에서 생산된 피노 누아로, 잘 익은 체리와 라즈베리 향이 특징이며, 부드러운 탄닌이 매력적인 레드 와인입니다.",
    "price": 60000,
    "tasteDescription": "체리와 라즈베리의 풍부한 과일 향",
    "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/74._%E1%84%89%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A6%E1%84%80%E1%85%A8_%E1%84%85%E1%85%A1_%E1%84%87%E1%85%A6%E1%86%AF_%E1%84%8B%E1%85%A1%E1%86%BC%E1%84%8C%E1%85%A6%E1%86%AF%E1%84%85%E1%85%B3_%E1%84%91%E1%85%B5%E1%84%82%E1%85%A9%E1%84%82%E1%85%AE%E1%84%8B%E1%85%A1.png"
  },
  {
    "name": "돔 페리뇽 빈티지",
    "type": "샴페인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "프랑스",
    "alcohol": 12.5,
    "rating": 4.9,
    "description": "프랑스 샴페인 지역의 빈티지 샴페인으로, 복합적인 풍미와 섬세한 기포가 특징입니다.",
    "price": 250000,
    "tasteDescription": "복합적인 과일 향과 섬세한 기포",
    "image": "https://awine.kr/wp-content/uploads/vb_wine_img/13501.png"
},
{
    "name": "모엣 샹동 임페리얼 브뤼",
    "type": "샴페인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "프랑스",
    "alcohol": 12.0,
    "rating": 4.8,
    "description": "프랑스 샴페인 하우스 모엣 샹동의 대표 샴페인으로, 사과와 브리오슈 향이 특징입니다.",
    "price": 150000,
    "tasteDescription": "사과와 브리오슈의 섬세한 향",
    "image": "https://awine.kr/wp-content/uploads/vb_wine_img/437.png"
},
{
  "name": "카스티오 데 메티에라 아틀란티스 알바리뇨",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "스페인",
  "alcohol": 12.5,
  "rating": 4.5,
  "description": "스페인 리아스 바이샤스 지역의 알바리뇨 와인으로, 시트러스와 미네랄 풍미가 어우러진 신선한 맛이 특징입니다.",
  "price": 32000,
  "tasteDescription": "밝은 시트러스와 미네랄 풍미",
  "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/104.%E1%84%8F%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%8B%E1%85%A6%E1%86%AB%E1%84%8C%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%8B%E1%85%AA%E1%84%8B%E1%85%B5%E1%86%AB_%E1%84%87%E1%85%A9%E1%84%83%E1%85%A6%E1%84%80%E1%85%A1%E1%84%89%E1%85%B3-%E1%84%8F%E1%85%A1%E1%84%89%E1%85%B3%E1%84%83%E1%85%B5%E1%84%8B%E1%85%A9-%E1%84%83%E1%85%A6-%E1%84%86%E1%85%A6%E1%84%90%E1%85%B5%E1%84%8B%E1%85%A6%E1%84%85%E1%85%A1-%E1%84%8B%E1%85%A1%E1%84%90%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A1%E1%86%AB%E1%84%90%E1%85%B5%E1%84%89%E1%85%B3-%E1%84%8B%E1%85%A1%E1%86%AF%E1%84%87%E1%85%A1%E1%84%85%E1%85%B5%E1%84%82%E1%85%AD.png"
},
{
    "name": "산타 마르게리타 피노 그리지오",
    "type": "화이트 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "이탈리아",
    "alcohol": 12.5,
    "rating": 4.4,
    "description": "이탈리아 베네토 지역에서 생산된 상큼한 피노 그리지오로, 과일 향이 가득한 깔끔한 화이트 와인입니다.",
    "price": 40000,
    "tasteDescription": "과일 향과 깔끔한 피니시",
    "image": "https://dohkqc1a6ll6k.cloudfront.net/eyJidWNrZXQiOiJ3aW5lZ3JhcGgtcHJvZHVjdGlvbiIsImtleSI6IndpbmVzL2JpXzYyNy5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsiZml0IjoiY29udGFpbiIsIndpZHRoIjozMjB9fX0=?signature=a18c286f39dfe96f8cb6459b0e0f69309f92de5f0061c6ae3f7eded9246033cf"
},
{
  "name": "덕혼 빈야드 나파 밸리 샤도네이",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "미국",
  "alcohol": 13.9,
  "rating": 4.6,
  "description": "미국 나파 밸리에서 생산된 고급 샤도네이 와인으로, 열대 과일과 은은한 오크 향이 조화로운 풍미를 선사합니다.",
  "price": 75000,
  "tasteDescription": "열대 과일과 오크의 풍미",
  "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/46.%E1%84%82%E1%85%A1%E1%84%85%E1%85%A1%E1%84%89%E1%85%A6%E1%86%AF%E1%84%85%E1%85%A1_%E1%84%83%E1%85%A5%E1%86%A8%E1%84%92%E1%85%A9%E1%86%AB-%E1%84%87%E1%85%B5%E1%86%AB%E1%84%8B%E1%85%A3%E1%84%83%E1%85%B3-%E1%84%82%E1%85%A1%E1%84%91%E1%85%A1-%E1%84%87%E1%85%A2%E1%86%AF%E1%84%85%E1%85%B5-%E1%84%89%E1%85%A3%E1%84%83%E1%85%A9%E1%84%82%E1%85%A6%E1%84%8B%E1%85%B5.png"
},
{
    "name": "마르께스 데 까사 콘차",
    "type": "레드 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "칠레",
    "alcohol": 14.0,
    "rating": 4.4,
    "description": "칠레의 대표 레드 와인으로, 체리와 초콜릿의 농축된 향이 인상적입니다.",
    "price": 45000,
    "tasteDescription": "농축된 체리와 초콜릿 향",
    "image": "https://m.wineall.co.kr/web/product/big/202201/7cc144b7bb44157e4d2a832e55520adb.png"
},
{
    "name": "아말라야 말벡",
    "type": "레드 와인",
    "category": "양조주",
    "subCategory": "와인",
    "origin": "아르헨티나",
    "alcohol": 13.5,
    "rating": 4.5,
    "description": "아르헨티나 살타 지역의 말벡 와인으로, 짙은 과일 향과 부드러운 타닌이 특징입니다.",
    "price": 30000,
    "tasteDescription": "짙은 과일 향과 부드러운 타닌",
    "image": "https://haywines.co.uk/cdn/shop/products/ARG-Amalaya-Tinto-1.jpg?v=1653484906"
},
{
  "name": "체레토 바롤로",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "이탈리아",
  "alcohol": 14.0,
  "rating": 4.6,
  "description": "이탈리아 피에몬테 지역의 바롤로 와인으로, 체리와 자두의 진한 과일 향과 함께 부드러운 타닌이 돋보입니다.",
  "price": 85000,
  "tasteDescription": "체리와 자두의 진한 향, 부드러운 타닌",
  "image": "https://awine.kr/wp-content/uploads/vb_wine_img/6157.png"
},
{
  "name": "테르아 비네다 멜로",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "이탈리아",
  "alcohol": 13.5,
  "rating": 4.3,
  "description": "이탈리아에서 생산된 멜로 와인으로, 잘 익은 딸기와 체리의 과일 향이 부드럽게 어우러진 와인입니다.",
  "price": 40000,
  "tasteDescription": "잘 익은 딸기와 체리의 부드러운 향",
  "image": "https://www.hwagangliquor.com/data/file/bostavan/833353719_meMdgIWV_0e86827fdf187f86da611476f4ae8a4a5d0c030d.jpg"
},
{
  "name": "끌로 뒤 물랑 오 무완 부르고뉴 '끌로 드 라 페리에르' 블랑",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 13.0,
  "rating": 4.7,
  "description": "프랑스 부르고뉴 지역의 고급 샤르도네로, 복숭아와 미네랄 풍미가 돋보이며 균형 잡힌 산미가 특징입니다.",
  "price": 90000,
  "tasteDescription": "복숭아와 미네랄 풍미, 균형 잡힌 산미",
  "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/266._%E1%84%87%E1%85%B5%E1%84%82%E1%85%A9%E1%84%8F%E1%85%AE%E1%84%89%E1%85%B3_%E1%84%81%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A9_%E1%84%83%E1%85%B1_%E1%84%86%E1%85%AE%E1%86%AF%E1%84%85%E1%85%A1%E1%86%BC_%E1%84%8B%E1%85%A9_%E1%84%86%E1%85%AE%E1%84%8B%E1%85%AA%E1%86%AB_%E1%84%87%E1%85%AE%E1%84%85%E1%85%B3%E1%84%80%E1%85%A9%E1%84%82%E1%85%B2_%E1%84%81%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A9_%E1%84%83%E1%85%B3_%E1%84%85%E1%85%A1_%E1%84%91%E1%85%A6%E1%84%85%E1%85%B5%E1%84%8B%E1%85%A6%E1%84%85%E1%85%B3_%E1%84%87%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A1%E1%86%BC.png"
},
{
  "name": "볼랭저 스페셜 큐베",
  "type": "샴페인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 12.0,
  "rating": 4.8,
  "description": "프랑스 샴페인 하우스 볼랭저의 특별한 샴페인으로, 구운 빵과 견과류의 풍미가 조화를 이룹니다.",
  "price": 120000,
  "tasteDescription": "구운 빵과 견과류의 고소한 향",
  "image": "https://www.gloriawines.com/cdn/shop/files/BollingerSpecialCuveeBrut_b6e9d3c5-a692-4a65-b4dd-386a748f38ff_1080x.jpg?v=1690906896"
},
{
  "name": "샤또 팔머",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 13.5,
  "rating": 4.7,
  "description": "프랑스 보르도 지역의 프리미엄 레드 와인으로, 진한 베리 향과 오크 풍미가 인상적입니다.",
  "price": 180000,
  "tasteDescription": "진한 베리 향과 오크의 조화",
  "image": "https://www.directwine.shop/cdn/shop/files/13242-chateau-palmer-alter-ego-de-palmer-h-800_600x.png?v=1715927543"
},
{
  "name": "프리머스 까르미네르",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "칠레",
  "alcohol": 13.0,
  "rating": 4.3,
  "description": "칠레에서 생산된 고급 까르미네르로, 과일의 풍미와 부드러운 타닌이 특징입니다.",
  "price": 40000,
  "tasteDescription": "풍부한 과일과 부드러운 타닌",
  "image": "https://cdn.veluga.kr/files/supplier/122/drinks/1808_Primus_The_blend.png"
},
{
  "name": "구스타브 로렌츠 게뷔르츠트라미너 리저브",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 13.5,
  "rating": 4.5,
  "description": "프랑스 알자스 지역의 고급 게뷔르츠트라미너로, 풍부한 꽃 향과 열대 과일 향이 특징인 화이트 와인입니다.",
  "price": 45000,
  "tasteDescription": "꽃 향과 열대 과일 향의 풍미",
  "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/291.%E1%84%82%E1%85%A1%E1%84%85%E1%85%A1%E1%84%89%E1%85%A6%E1%86%AF%E1%84%85%E1%85%A1_%E1%84%80%E1%85%AE%E1%84%89%E1%85%B3%E1%84%90%E1%85%A1%E1%84%87%E1%85%B3-%E1%84%85%E1%85%A9%E1%84%85%E1%85%A6%E1%86%AB%E1%84%8E%E1%85%B3-%E1%84%80%E1%85%A6%E1%84%87%E1%85%AE%E1%84%85%E1%85%B3%E1%84%8E%E1%85%B3%E1%84%90%E1%85%B3%E1%84%85%E1%85%A1%E1%84%86%E1%85%B5%E1%84%82%E1%85%A5-%E1%84%85%E1%85%B5%E1%84%8C%E1%85%A5%E1%84%87%E1%85%B3.png"
},
{
  "name": "돔 리슬링 트로켄",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "독일",
  "alcohol": 12.0,
  "rating": 4.4,
  "description": "독일산 리슬링 트로켄 와인으로, 상쾌한 산미와 그린 애플, 레몬의 신선한 향이 특징입니다.",
  "price": 40000,
  "tasteDescription": "그린 애플과 레몬의 신선한 산미",
  "image": "https://awine.kr/wp-content/uploads/vb_wine_img/7314.png"
},
{
  "name": "루이막스 마콩 빌라쥬",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 12.5,
  "rating": 4.3,
  "description": "프랑스 부르고뉴 지역에서 생산된 화이트 와인으로, 상쾌한 산미와 사과, 미네랄의 풍미가 조화로운 와인입니다.",
  "price": 42000,
  "tasteDescription": "사과와 미네랄의 산뜻한 풍미",
  "image": "https://m.wineall.co.kr/web/product/big/202201/2b3aecec76940b121f74407d3006d5b3.jpg"
},
{
  "name": "베가 시실리아 우니코",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "스페인",
  "alcohol": 14.0,
  "rating": 4.8,
  "description": "스페인 최고의 레드 와인 중 하나로, 깊은 체리와 초콜릿 풍미가 매력적입니다.",
  "price": 300000,
  "tasteDescription": "깊은 체리와 초콜릿의 풍미",
  "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/89._%E1%84%89%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A6%E1%84%80%E1%85%A8_%E1%84%87%E1%85%A6%E1%84%80%E1%85%A1_%E1%84%89%E1%85%B5%E1%84%89%E1%85%B5%E1%86%AF%E1%84%85%E1%85%B5%E1%84%8B%E1%85%A1_%E1%84%8B%E1%85%AE%E1%84%82%E1%85%B5%E1%84%8F%E1%85%A9.png"
},
{
  "name": "조셉 펠프스 인시그니아",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "미국",
  "alcohol": 14.5,
  "rating": 4.8,
  "description": "미국 나파 밸리의 프리미엄 레드 와인으로, 블랙베리와 카시스의 깊은 풍미와 우아한 오크 노트가 조화를 이룹니다.",
  "price": 250000,
  "tasteDescription": "블랙베리와 카시스의 깊은 풍미, 우아한 오크",
  "image": "https://www.directwine.shop/cdn/shop/products/outshinery-josephphelps-insignia-nv-1662648000443_600x_0d81b9c7-102f-47aa-8e97-8ac4dbeab52e.png?v=1678343947"
},
{
  "name": "카살레토 비안코",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "이탈리아",
  "alcohol": 12.0,
  "rating": 4.2,
  "description": "이탈리아의 상큼한 화이트 와인으로, 신선한 사과와 시트러스 향이 조화를 이루며 부드러운 질감이 특징입니다.",
  "price": 30000,
  "tasteDescription": "신선한 사과와 시트러스의 상큼한 향",
  "image": "https://cdn.veluga.kr/files/supplier/131/drinks/1978_Casaletto_Semi_Sweet_White.png"
},
{
  "name": "트라피체 말벡 리저브",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "아르헨티나",
  "alcohol": 13.5,
  "rating": 4.4,
  "description": "아르헨티나의 말벡 리저브 와인으로, 블랙베리와 초콜릿 향이 진하게 느껴집니다.",
  "price": 50000,
  "tasteDescription": "블랙베리와 초콜릿의 진한 향",
  "image": "https://dohkqc1a6ll6k.cloudfront.net/eyJidWNrZXQiOiJ3aW5lZ3JhcGgtcHJvZHVjdGlvbiIsImtleSI6IndpbmVzL2JpXzY0MC5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsiZml0IjoiY29udGFpbiIsIndpZHRoIjozMjB9fX0=?signature=22429fd086d37c15e921c344435a201261fdecbac04a11431dd2a4c71e486a90"
},
{
  "name": "루이 로드레 프리미에 브륏",
  "type": "샴페인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 12.0,
  "rating": 4.7,
  "description": "프랑스 샴페인 하우스 루이 로더러의 브륏 샴페인으로, 신선한 과일과 꽃 향이 돋보입니다.",
  "price": 120000,
  "tasteDescription": "신선한 과일과 꽃 향",
  "image": "https://awine.kr/wp-content/uploads/vb_wine_img/429.png"
},
{
  "name": "센데로 까베르네 소비뇽",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "칠레",
  "alcohol": 13.5,
  "rating": 4.3,
  "description": "칠레에서 생산된 센데로 까베르네 소비뇽으로, 잘 익은 체리와 블랙커런트의 진한 과일 풍미와 부드러운 탄닌이 특징입니다.",
  "price": 28000,
  "tasteDescription": "체리와 블랙커런트의 진한 풍미와 부드러운 탄닌",
  "image": "https://m.10000wine.co.kr/web/product/big/202110/6d75a495e8153ae2f4a37d17f087c2e8.jpg"
},
{
  "name": "르윈 에스테이트 아트시리즈 샤도네이",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "호주",
  "alcohol": 13.5,
  "rating": 4.8,
  "description": "호주 마가렛 리버 지역의 프리미엄 샤도네이로, 레몬과 복숭아, 파인애플의 풍부한 과일 향과 은은한 바닐라, 오크 노트가 조화를 이루는 와인입니다.",
  "price": 150000,
  "tasteDescription": "레몬과 복숭아, 파인애플의 풍부한 과일 향과 오크의 조화",
  "image": "https://awine.kr/wp-content/uploads/vb_wine_img/14891.png"
},
{
  "name": "반피 키안티 클라시코 리제르바",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "이탈리아",
  "alcohol": 13.0,
  "rating": 4.5,
  "description": "이탈리아 토스카나 지역의 키안티 클라시코 리제르바로, 체리와 자두의 풍부한 과일 향과 함께 스파이시한 노트가 조화를 이루는 와인입니다.",
  "price": 55000,
  "tasteDescription": "체리와 자두의 풍부한 과일 향과 스파이스의 조화",
  "image": "https://www.directwine.shop/cdn/shop/files/10989-banfi-chianti-classico-riserva-h-800.png?v=1718793664"
},
{
  "name": "라 크레마 피노 누아",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "미국",
  "alcohol": 13.9,
  "rating": 4.6,
  "description": "캘리포니아 소노마 지역의 피노 누아로, 라즈베리와 스파이스 향이 돋보입니다.",
  "price": 65000,
  "tasteDescription": "라즈베리와 스파이스의 향미",
  "image": "https://cdn.veluga.kr/files/supplier/156/drinks/%EB%9D%BC_%ED%81%AC%EB%A0%88%EB%A7%88_%EB%AA%AC%ED%85%8C%EB%A0%88%EC%9D%B4_%ED%94%BC%EB%85%B8%EB%88%84%EC%95%84_La_Crema_Monterey_Pinot_Noir_%EB%82%98%EB%9D%BC%EC%85%80%EB%9D%BC.png"
},
{
  "name": "모알라 샤블리 그랑 크뤼 부그로",
  "type": "화이트 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 13.0,
  "rating": 4.7,
  "description": "프랑스 샤블리 지역의 최고 등급인 그랑 크뤼 부그로에서 생산된 샤르도네로, 미네랄과 신선한 사과 향이 조화를 이루며 우아한 산미가 특징입니다.",
  "price": 120000,
  "tasteDescription": "미네랄과 신선한 사과 향, 우아한 산미",
  "image": "https://stage-cdn.veluga.kr/files/supplier/undefined/drinks/60.%E1%84%92%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%B3%E1%84%8C%E1%85%B5%E1%86%AB%E1%84%85%E1%85%A9_%E1%84%86%E1%85%A9%E1%84%8B%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A1_%E1%84%89%E1%85%A3%E1%84%87%E1%85%B3%E1%86%AF%E1%84%85%E1%85%B5_%E1%84%80%E1%85%B3%E1%84%85%E1%85%A1%E1%86%BC_%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B1_%E1%84%87%E1%85%AE%E1%84%80%E1%85%B3%E1%84%85%E1%85%A9.png"
},
{
  "name": "드라피에 브륏 내추럴",
  "type": "샴페인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 12.0,
  "rating": 4.6,
  "description": "프랑스 드라피에 샴페인의 브륏 내추럴로, 신선한 과일과 꽃 향이 조화롭습니다.",
  "price": 100000,
  "tasteDescription": "신선한 과일과 꽃 향의 조화",
  "image": "https://stage-cdn.veluga.kr/files/supplier/186/drinks/11._csr_%E1%84%89%E1%85%A3%E1%86%B7%E1%84%91%E1%85%A6%E1%84%8B%E1%85%B5%E1%86%AB_%E1%84%83%E1%85%B3%E1%84%85%E1%85%A1%E1%84%91%E1%85%B5%E1%84%8B%E1%85%A6_%E1%84%87%E1%85%B3%E1%84%85%E1%85%B1%E1%86%BA_%E1%84%82%E1%85%A1%E1%84%84%E1%85%AE%E1%84%85%E1%85%B3_%E1%84%8C%E1%85%A6%E1%84%85%E1%85%A9_%E1%84%83%E1%85%A9%E1%84%8C%E1%85%A1%E1%84%8C%E1%85%B2_%E1%84%89%E1%85%A1%E1%86%BC_%E1%84%89%E1%85%AE%E1%84%91%E1%85%B3%E1%84%85%E1%85%B3_nv.png"
},
{
  "name": "폴 드 코스트, 블랑 드 블랑 브룻",
  "type": "샴페인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 12.0,
  "rating": 4.4,
  "description": "프랑스에서 생산된 블랑 드 블랑 브룻 샴페인으로, 청사과와 시트러스의 신선한 향과 부드러운 기포가 특징입니다.",
  "price": 85000,
  "tasteDescription": "청사과와 시트러스의 신선한 향과 부드러운 기포",
  "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/110.%E1%84%87%E1%85%B5%E1%84%82%E1%85%A6%E1%84%89%E1%85%A6%E1%86%AB_%E1%84%91%E1%85%A9%E1%86%AF_%E1%84%83%E1%85%B3_%E1%84%8F%E1%85%A9%E1%84%89%E1%85%B3%E1%84%90%E1%85%B3_%E1%84%87%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A1%E1%86%BC_%E1%84%83%E1%85%B3_%E1%84%87%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A1%E1%86%BC_%E1%84%87%E1%85%B3%E1%84%85%E1%85%AE%E1%86%BA.png"
},
{
  "name": "산타 리타 메를로",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "칠레",
  "alcohol": 13.5,
  "rating": 4.2,
  "description": "칠레의 부드러운 메를로 와인으로, 베리와 초콜릿의 풍미가 특징입니다.",
  "price": 32000,
  "tasteDescription": "베리와 초콜릿의 부드러운 풍미",
  "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/460.%E1%84%85%E1%85%A9%E1%86%BA%E1%84%83%E1%85%A6%E1%84%8E%E1%85%B5%E1%86%AF%E1%84%89%E1%85%A5%E1%86%BC_%E1%84%89%E1%85%A1%E1%86%AB%E1%84%90%E1%85%A1%E1%84%85%E1%85%B5%E1%84%90%E1%85%A1_%E1%84%85%E1%85%B5%E1%84%8C%E1%85%A6%E1%84%85%E1%85%B3%E1%84%87%E1%85%A1_%E1%84%86%E1%85%A6%E1%84%85%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A9.png"
},
{
  "name": "세바스티앙 베쏭 모르공",
  "type": "레드 와인",
  "category": "양조주",
  "subCategory": "와인",
  "origin": "프랑스",
  "alcohol": 13.0,
  "rating": 4.6,
  "description": "프랑스 보졸레 지역의 모르공에서 생산된 가메이 품종의 레드 와인으로, 잘 익은 체리와 라즈베리의 풍부한 과일 향이 특징이며 부드러운 탄닌이 매력적입니다.",
  "price": 60000,
  "tasteDescription": "잘 익은 체리와 라즈베리의 풍부한 과일 향과 부드러운 탄닌",
  "image": "https://files.vitis.co.kr/prod/images/vitis_0080e4382d4445aa907476a7f9e8aaad.jpg"
},
      //증류주 50개
      {
        name: "글렌피딕 12년산",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.5,
        description: "신선한 사과와 배, 바닐라와 오크의 미묘한 맛이 조화를 이룹니다.",
        price: 70000,
        tasteDescription: "사과와 배, 바닐라, 오크",
        image: "https://cafe24.poxo.com/ec01/yms2310/HOvhRhvOk+Cp2KY4JuusAkTsbIYINUK2VSIGmcb5x6rWbiVFKFLJiOWiKTlmhPfGrqEqVOht/QNAz2W0Hrz3hg==/_/web/product/big/20200505/dee6086e60ca279582edfc8187d8831c.jpg"
      },
      {
        name: "조니 워커 블루 라벨",
        type: "블렌디드 스카치",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.9,
        description: "풍부하고 복합적인 맛, 부드러운 마무리가 특징인 프리미엄 블렌디드 위스키.",
        price: 230000,
        tasteDescription: "풍부한 과일, 스모키, 바닐라",
        image: "https://img3.cyberskyshop.com:8443/web/upload/prd/S01069F0/20171101162108685023.png"
      },
      {
        name: "라프로익 10년산",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.7,
        description: "강렬한 피트 향과 바다의 염분이 조화를 이룬 독특한 맛이 특징입니다.",
        price: 85000,
        tasteDescription: "피트, 바다 염분, 바닐라",
        image: "https://m.10000wine.co.kr/web/product/big/202307/d0b23e62b3eeafe3b97feee9acfc3a9b.png"
      },
      {
        name: "발베니 더블우드 12년산",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.6,
        description: "오크통과 쉐리통 숙성의 복합적인 풍미가 특징인 싱글 몰트 위스키.",
        price: 100000,
        tasteDescription: "오크, 쉐리, 말린 과일",
        image: "https://cdn.veluga.kr/files/supplier/undefined/drinks/13.%E1%84%8B%E1%85%B1%E1%86%AF%E1%84%85%E1%85%B5%E1%84%8B%E1%85%A5%E1%86%B7%E1%84%80%E1%85%B3%E1%84%85%E1%85%A2%E1%86%AB%E1%84%90%E1%85%B3_%E1%84%87%E1%85%A1%E1%86%AF%E1%84%87%E1%85%A6%E1%84%82%E1%85%B512%E1%84%82%E1%85%A7%E1%86%AB%E1%84%83%E1%85%A5%E1%84%87%E1%85%B3%E1%86%AF%E1%84%8B%E1%85%AE%E1%84%83%E1%85%B3.png"
      },
      {
        name: "맥캘란 12년 더블 캐스크",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "스코틀랜드",
        alcohol: 40,
        rating: 4.8,
        description: "미국산 오크통과 유럽산 오크통에서 숙성된 부드럽고 달콤한 위스키.",
        price: 120000,
        tasteDescription: "꿀, 시트러스, 오크",
        image: "https://cdn.veluga.kr/files/supplier/217/drinks/%EB%A7%A5%EC%BA%98%EB%9E%80_12%EB%85%84_%EB%8D%94%EB%B8%94_%EC%BA%90%EC%8A%A4%ED%81%AC_The_Macallan_12yo_Double_Cask_%EB%94%94%EC%95%A4%ED%94%BC%EC%8A%A4%ED%94%BC%EB%A6%AC%EC%B8%A0.png"
      },
      {
        name: "잭 다니엘스 테네시 위스키",
        type: "테네시 위스키",
        category: "증류주",
        subCategory: "위스키",
        origin: "미국",
        alcohol: 40,
        rating: 4.5,
        description: "부드러운 스모키한 맛과 달콤한 캐러멜 향이 조화를 이루는 테네시 위스키.",
        price: 40000,
        tasteDescription: "스모키, 캐러멜, 바닐라",
        image: "https://mcgrocer.com/cdn/shop/files/62176011_0_640x640_3fc75c53-6353-425c-8777-a1cb122d7ff7.jpg?v=1723875012"
      },
      {
        name: "카발란 솔리스트 셰리 캐스크",
        type: "싱글 몰트",
        category: "증류주",
        subCategory: "위스키",
        origin: "대만",
        alcohol: 58.6,
        rating: 4.7,
        description: "대만의 대표적인 싱글 몰트 위스키로, 진한 셰리 향과 몰트의 깊은 맛이 특징입니다.",
        price: 250000,
        tasteDescription: "셰리, 말린 과일, 초콜릿",
        image: "https://drunkn-monkey.com/data/mall/68/6/6708720230509161333.thumb.jpg"
      },
      {
        name: "바카디 골드 럼",
        type: "럼",
        category: "증류주",
        subCategory: "럼",
        origin: "푸에르토리코",
        alcohol: 40,
        rating: 4.3,
        description: "달콤한 바닐라와 오크 향이 가미된 부드러운 럼, 칵테일 베이스로 좋습니다.",
        price: 30000,
        tasteDescription: "바닐라, 오크, 토피",
        image: "https://lh5.googleusercontent.com/proxy/5OmHu9PZ8tr79e6DAUUvFhwpdYhjE2C9xZVDRM7H-e-EfyR_6srVcJkSckG5gxN8LkOYP96FvuFGYkfufdWGNHA"
      },
      {
        name: "앱솔루트 보드카",
        type: "보드카",
        category: "증류주",
        subCategory: "보드카",
        origin: "스웨덴",
        alcohol: 40,
        rating: 4.4,
        description: "깨끗하고 부드러운 맛이 특징인 스웨덴의 대표적인 보드카.",
        price: 25000,
        tasteDescription: "깨끗한 맛, 약간의 곡물 향",
        image: "https://m.wineall.co.kr/web/product/big/202401/87705ec603d8eb30499bcf1f46e1b147.png"
      },
      {
        name: "패트론 실버 테킬라",
        type: "테킬라",
        category: "증류주",
        subCategory: "테킬라",
        origin: "멕시코",
        alcohol: 40,
        rating: 4.6,
        description: "멕시코의 대표적인 고급 테킬라로, 깔끔하고 상쾌한 아가베 맛이 특징입니다.",
        price: 60000,
        tasteDescription: "아가베, 시트러스, 허브",
        image: "https://cdn.hddfs.com/files/goos/0816/20240717/ba61cc55.jpg?sf=webp&RS=340x340"
      },
      {
        "name": "핸드릭스 진",
        "type": "진",
        "category": "증류주",
        "subCategory": "진",
        "origin": "스코틀랜드",
        "alcohol": 41.4,
        "rating": 4.6,
        "description": "독특한 오이와 장미 향이 어우러진 프리미엄 진으로, 칵테일 베이스로 인기가 많습니다.",
        "price": 55000,
        "tasteDescription": "오이와 장미, 허브",
        "image": "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fb2FSHe%2Fbtr1Wl2BBdK%2F2Q98AM2xSGd8lDGRohiqCK%2Fimg.png"
    },
    {
        "name": "레미 마르탱 XO",
        "type": "코냑",
        "category": "증류주",
        "subCategory": "브랜디",
        "origin": "프랑스",
        "alcohol": 40,
        "rating": 4.9,
        "description": "깊은 과일 향과 오크 향이 조화를 이루는 프랑스 코냑으로, 프리미엄 XO 등급입니다.",
        "price": 250000,
        "tasteDescription": "자두와 건포도, 오크",
        "image": "https://duty-free-japan.jp/haneda/ko/images/item/5101200016.jpg"
    },
    {
        "name": "벨베데레 보드카",
        "type": "보드카",
        "category": "증류주",
        "subCategory": "보드카",
        "origin": "폴란드",
        "alcohol": 40,
        "rating": 4.5,
        "description": "고급 수수로 만든 부드러운 보드카로, 깨끗한 맛과 은은한 곡물 향이 특징입니다.",
        "price": 45000,
        "tasteDescription": "깨끗한 곡물 향",
        "image": "https://lh4.googleusercontent.com/proxy/dlTqNV07eQPxa3zdXn9kGq2q_XarBkqjEx7Jv2l3I4rtKPhlDNxUwvY40aaR4eGt2dAzptrOTWpJDs7I1PY_NX13oqK5ZbQk5SpAur3J2R4T0AFuQFQUmj8gGzQ1Wg"
    },
    {
        "name": "제임슨 아이리시 위스키",
        "type": "아이리시 위스키",
        "category": "증류주",
        "subCategory": "위스키",
        "origin": "아일랜드",
        "alcohol": 40,
        "rating": 4.6,
        "description": "아일랜드의 대표적인 부드럽고 달콤한 몰트 맛이 특징인 아이리시 위스키입니다.",
        "price": 40000,
        "tasteDescription": "부드러운 몰트와 약간의 과일 향",
        "image": "https://m.goldcompany.co.kr/web/product/big/202211/3f9ce47ea102e62cbc2394e36bc1ce0e.jpg"
    },
    {
        "name": "피스코 소우어",
        "type": "피스코",
        "category": "증류주",
        "subCategory": "브랜디",
        "origin": "페루",
        "alcohol": 40,
        "rating": 4.4,
        "description": "페루에서 유래한 피스코로, 상큼한 과일 향과 부드러운 마무리가 특징입니다.",
        "price": 50000,
        "tasteDescription": "상큼한 과일 향",
        "image": "https://cdn.veluga.kr/files/supplier/undefined/drinks/34.%E1%84%8B%E1%85%B2%E1%84%91%E1%85%B5%E1%86%A8_%E1%84%90%E1%85%A1%E1%84%87%E1%85%A6%E1%84%85%E1%85%B3%E1%84%82%E1%85%A6%E1%84%85%E1%85%A9_%E1%84%91%E1%85%B5%E1%84%89%E1%85%B3%E1%84%8F%E1%85%A9_%E1%84%8B%E1%85%A1%E1%84%8E%E1%85%A9%E1%84%85%E1%85%A1%E1%84%83%E1%85%A9.png"
    },
    {
        "name": "샤르트뢰즈",
        "type": "리큐어",
        "category": "증류주",
        "subCategory": "리큐어",
        "origin": "프랑스",
        "alcohol": 55,
        "rating": 4.7,
        "description": "수도승이 만든 프랑스의 고급 리큐어로, 약초와 스파이스가 어우러진 풍미가 특징입니다.",
        "price": 70000,
        "tasteDescription": "약초와 스파이스의 깊은 향",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvq-r27BIgTiOotsSOls0QXdWzuGeBzWhSaQ&s"
    },
    {
        "name": "애플턴 에스테이트 자메이카 럼",
        "type": "럼",
        "category": "증류주",
        "subCategory": "럼",
        "origin": "자메이카",
        "alcohol": 43,
        "rating": 4.5,
        "description": "자메이카의 전통 럼으로, 진한 카라멜과 열대 과일 향이 특징입니다.",
        "price": 35000,
        "tasteDescription": "카라멜과 열대 과일",
        "image": "https://mcgrocer.com/cdn/shop/products/348955011_0_640x640_9514414e-9340-4e3b-9f66-99948de9e9f7.jpg?v=1670001876"
    },
    {
        "name": "불러바드 쿤스 리큐어",
        "type": "리큐어",
        "category": "증류주",
        "subCategory": "리큐어",
        "origin": "프랑스",
        "alcohol": 30,
        "rating": 4.6,
        "description": "프랑스의 고급 리큐어로, 자몽과 레몬 향이 특징이며, 달콤한 맛이 매력적입니다.",
        "price": 45000,
        "tasteDescription": "자몽과 레몬의 산뜻함",
        "image": "https://example.com/bulleit_kunis_liqueur.jpg"
    },
    {
        "name": "키케로 하이랜드 진",
        "type": "진",
        "category": "증류주",
        "subCategory": "진",
        "origin": "스페인",
        "alcohol": 43.5,
        "rating": 4.5,
        "description": "스페인의 프리미엄 진으로, 상쾌한 허브와 약간의 과일 향이 어우러져 있습니다.",
        "price": 48000,
        "tasteDescription": "허브와 과일 향",
        "image": "https://example.com/cicero_highland_gin.jpg"
    },
    {
        "name": "탄케레이 넘버 텐",
        "type": "진",
        "category": "증류주",
        "subCategory": "진",
        "origin": "영국",
        "alcohol": 47.3,
        "rating": 4.8,
        "description": "영국의 프리미엄 진으로, 상큼한 시트러스 향과 허브 향이 매력적입니다.",
        "price": 60000,
        "tasteDescription": "시트러스와 허브의 상쾌한 향",
        "image": "https://example.com/tanqueray_no_ten.jpg"
    },
    {
      "name": "버팔로 트레이스 버번",
      "type": "버번 위스키",
      "category": "증류주",
      "subCategory": "위스키",
      "origin": "미국",
      "alcohol": 45,
      "rating": 4.5,
      "description": "미국에서 생산된 전통적인 버번으로, 바닐라와 카라멜, 스파이스 향이 조화를 이룹니다.",
      "price": 40000,
      "tasteDescription": "바닐라, 카라멜, 스파이스",
      "image": "https://example.com/buffalo_trace.jpg"
  },
  {
      "name": "미도리 멜론 리큐어",
      "type": "리큐어",
      "category": "증류주",
      "subCategory": "리큐어",
      "origin": "일본",
      "alcohol": 20,
      "rating": 4.3,
      "description": "멜론의 달콤한 풍미로 유명한 일본산 리큐어로, 칵테일에 사용되며 달콤한 맛이 매력적입니다.",
      "price": 25000,
      "tasteDescription": "달콤한 멜론 향",
      "image": "https://example.com/midori_liqueur.jpg"
  },
  {
      "name": "와일드 터키 101",
      "type": "버번 위스키",
      "category": "증류주",
      "subCategory": "위스키",
      "origin": "미국",
      "alcohol": 50.5,
      "rating": 4.7,
      "description": "높은 도수의 강렬한 버번으로, 스파이스와 캐러멜의 진한 풍미가 특징입니다.",
      "price": 60000,
      "tasteDescription": "스파이스, 캐러멜, 오크",
      "image": "https://example.com/wild_turkey_101.jpg"
  },
  {
      "name": "시에라 실버 테킬라",
      "type": "테킬라",
      "category": "증류주",
      "subCategory": "테킬라",
      "origin": "멕시코",
      "alcohol": 38,
      "rating": 4.3,
      "description": "멕시코산 실버 테킬라로, 아가베의 상큼함과 가벼운 허브 향이 어우러집니다.",
      "price": 35000,
      "tasteDescription": "아가베, 허브, 상쾌함",
      "image": "https://example.com/sierra_silver_tequila.jpg"
  },
  {
      "name": "카르타 블랑카",
      "type": "럼",
      "category": "증류주",
      "subCategory": "럼",
      "origin": "쿠바",
      "alcohol": 37.5,
      "rating": 4.2,
      "description": "쿠바에서 생산되는 클래식 화이트 럼으로, 상쾌한 바닐라와 가벼운 오크 향이 특징입니다.",
      "price": 30000,
      "tasteDescription": "바닐라와 오크의 상쾌함",
      "image": "https://example.com/carta_blanca.jpg"
  },
  {
      "name": "바네스 오리지널",
      "type": "보드카",
      "category": "증류주",
      "subCategory": "보드카",
      "origin": "러시아",
      "alcohol": 40,
      "rating": 4.5,
      "description": "러시아의 고급 보드카로, 깨끗하고 부드러운 맛이 특징이며, 약간의 곡물 향을 느낄 수 있습니다.",
      "price": 32000,
      "tasteDescription": "깨끗한 곡물 향",
      "image": "https://example.com/banes_original.jpg"
  },
  {
      "name": "바이욘 브랜디",
      "type": "브랜디",
      "category": "증류주",
      "subCategory": "브랜디",
      "origin": "스페인",
      "alcohol": 38,
      "rating": 4.4,
      "description": "스페인산 브랜디로, 건포도와 오크 향이 잘 어우러진 깊은 풍미가 특징입니다.",
      "price": 45000,
      "tasteDescription": "건포도와 오크 향",
      "image": "https://example.com/bayon_brandy.jpg"
  },
  {
      "name": "디사로노 아마레토",
      "type": "리큐어",
      "category": "증류주",
      "subCategory": "리큐어",
      "origin": "이탈리아",
      "alcohol": 28,
      "rating": 4.6,
      "description": "이탈리아산 아마레토 리큐어로, 아몬드와 바닐라의 달콤한 향이 특징입니다.",
      "price": 40000,
      "tasteDescription": "아몬드와 바닐라",
      "image": "https://example.com/disaronno_amaretto.jpg"
  },
  {
      "name": "빌스코치 블랙",
      "type": "블렌디드 스카치 위스키",
      "category": "증류주",
      "subCategory": "위스키",
      "origin": "스코틀랜드",
      "alcohol": 40,
      "rating": 4.4,
      "description": "스코틀랜드산 블렌디드 스카치로, 스모키와 과일 향이 조화를 이루는 균형 잡힌 위스키입니다.",
      "price": 55000,
      "tasteDescription": "스모키, 과일, 오크",
      "image": "https://example.com/billscotch_black.jpg"
  },
  {
      "name": "베네딕틴 D.O.M 리큐어",
      "type": "리큐어",
      "category": "증류주",
      "subCategory": "리큐어",
      "origin": "프랑스",
      "alcohol": 40,
      "rating": 4.5,
      "description": "프랑스의 허브 리큐어로, 다양한 허브와 스파이스가 조화를 이루며 달콤한 맛이 특징입니다.",
      "price": 60000,
      "tasteDescription": "허브와 스파이스, 달콤함",
      "image": "https://example.com/benedictine_dom.jpg"
  },
  {
    "name": "포트 샬럿 10년",
    "type": "싱글 몰트 위스키",
    "category": "증류주",
    "subCategory": "위스키",
    "origin": "스코틀랜드",
    "alcohol": 50,
    "rating": 4.6,
    "description": "아일라 섬에서 생산된 강렬한 피트 향과 복합적인 풍미가 특징인 싱글 몰트 위스키입니다.",
    "price": 120000,
    "tasteDescription": "피트, 스모크, 오크",
    "image": "https://example.com/port_charlotte_10.jpg"
},
{
    "name": "라가불린 16년",
    "type": "싱글 몰트 위스키",
    "category": "증류주",
    "subCategory": "위스키",
    "origin": "스코틀랜드",
    "alcohol": 43,
    "rating": 4.8,
    "description": "강렬한 피트와 스모키한 맛이 특징인 아이코닉 싱글 몰트 위스키.",
    "price": 160000,
    "tasteDescription": "피트, 스모크, 오크",
    "image": "https://example.com/lagavulin_16.jpg"
},
{
    "name": "하바나 클럽 7년",
    "type": "럼",
    "category": "증류주",
    "subCategory": "럼",
    "origin": "쿠바",
    "alcohol": 40,
    "rating": 4.5,
    "description": "쿠바산 프리미엄 럼으로, 깊고 진한 과일 향과 오크 풍미가 조화롭습니다.",
    "price": 45000,
    "tasteDescription": "과일, 오크, 바닐라",
    "image": "https://example.com/havana_club_7.jpg"
},
{
    "name": "그랑 마니에르 코디알",
    "type": "리큐어",
    "category": "증류주",
    "subCategory": "리큐어",
    "origin": "프랑스",
    "alcohol": 40,
    "rating": 4.7,
    "description": "오렌지와 코냑이 조화를 이루는 프랑스산 리큐어로, 깊은 오렌지 향이 특징입니다.",
    "price": 60000,
    "tasteDescription": "오렌지, 코냑",
    "image": "https://example.com/grand_marnier.jpg"
},
{
    "name": "럼 차타",
    "type": "리큐어",
    "category": "증류주",
    "subCategory": "리큐어",
    "origin": "미국",
    "alcohol": 13.75,
    "rating": 4.6,
    "description": "크림과 시나몬, 바닐라의 풍미가 조화를 이루는 달콤한 리큐어입니다.",
    "price": 30000,
    "tasteDescription": "시나몬, 바닐라, 크림",
    "image": "https://example.com/rum_chata.jpg"
},
{
    "name": "발레로스 블랙 라벨",
    "type": "블렌디드 스카치",
    "category": "증류주",
    "subCategory": "위스키",
    "origin": "스코틀랜드",
    "alcohol": 40,
    "rating": 4.4,
    "description": "풍부한 과일과 스모키함이 어우러진 블렌디드 스카치 위스키.",
    "price": 55000,
    "tasteDescription": "과일, 스모크, 오크",
    "image": "https://example.com/ballers_black.jpg"
},
{
    "name": "다빈치 에스프레소 리큐어",
    "type": "리큐어",
    "category": "증류주",
    "subCategory": "리큐어",
    "origin": "이탈리아",
    "alcohol": 28,
    "rating": 4.5,
    "description": "깊은 에스프레소 향과 달콤함이 조화를 이룬 커피 리큐어입니다.",
    "price": 35000,
    "tasteDescription": "커피, 초콜릿",
    "image": "https://example.com/da_vinci_espresso.jpg"
},
{
    "name": "피츠 제럴드 오리지널",
    "type": "버번 위스키",
    "category": "증류주",
    "subCategory": "위스키",
    "origin": "미국",
    "alcohol": 45,
    "rating": 4.6,
    "description": "미국산 클래식 버번으로, 달콤한 바닐라와 오크의 풍미가 특징입니다.",
    "price": 50000,
    "tasteDescription": "바닐라, 오크",
    "image": "https://example.com/fitzgerald_original.jpg"
},
{
    "name": "윌렛 포트 포유",
    "type": "싱글 배럴 버번",
    "category": "증류주",
    "subCategory": "위스키",
    "origin": "미국",
    "alcohol": 63,
    "rating": 4.7,
    "description": "단일 배럴에서 나오는 독특한 풍미와 강렬한 맛이 특징인 버번 위스키.",
    "price": 90000,
    "tasteDescription": "스파이스, 오크, 캐러멜",
    "image": "https://example.com/willett_pot.jpg"
},
{
    "name": "마르니에 피치 리큐어",
    "type": "리큐어",
    "category": "증류주",
    "subCategory": "리큐어",
    "origin": "프랑스",
    "alcohol": 35,
    "rating": 4.6,
    "description": "복숭아와 오렌지 향이 어우러진 달콤한 리큐어입니다.",
    "price": 30000,
    "tasteDescription": "복숭아, 오렌지",
    "image": "https://example.com/marnier_peach.jpg"
},
{
    "name": "엘도라도 15년",
    "type": "럼",
    "category": "증류주",
    "subCategory": "럼",
    "origin": "가이아나",
    "alcohol": 43,
    "rating": 4.8,
    "description": "가이아나산 프리미엄 럼으로, 복합적인 과일과 스파이스 풍미가 깊이감 있게 어우러집니다.",
    "price": 100000,
    "tasteDescription": "과일, 스파이스, 오크",
    "image": "https://example.com/eldorado_15.jpg"
},
{
    "name": "킨토리 진",
    "type": "진",
    "category": "증류주",
    "subCategory": "진",
    "origin": "일본",
    "alcohol": 43,
    "rating": 4.7,
    "description": "산뜻한 시트러스 향과 허브가 조화를 이룬 일본산 진.",
    "price": 65000,
    "tasteDescription": "시트러스, 허브",
    "image": "https://example.com/kintory_gin.jpg"
},
{
    "name": "그레이 구스",
    "type": "보드카",
    "category": "증류주",
    "subCategory": "보드카",
    "origin": "프랑스",
    "alcohol": 40,
    "rating": 4.8,
    "description": "프랑스의 프리미엄 보드카로, 부드럽고 깨끗한 맛이 특징입니다.",
    "price": 60000,
    "tasteDescription": "깨끗한 곡물 향",
    "image": "https://example.com/grey_goose.jpg"
},
{
    "name": "플레멩코 테킬라",
    "type": "테킬라",
    "category": "증류주",
    "subCategory": "테킬라",
    "origin": "멕시코",
    "alcohol": 38,
    "rating": 4.4,
    "description": "멕시코의 고급 테킬라로, 아가베의 달콤함과 시트러스 향이 조화롭습니다.",
    "price": 55000,
    "tasteDescription": "아가베, 시트러스",
    "image": "https://example.com/flamenco_tequila.jpg"
},
{
    "name": "바이쏘보드카",
    "type": "보드카",
    "category": "증류주",
    "subCategory": "보드카",
    "origin": "폴란드",
    "alcohol": 40,
    "rating": 4.3,
    "description": "폴란드산 보드카로, 전통 수수로 만들어 부드럽고 깨끗한 맛이 특징입니다.",
    "price": 35000,
    "tasteDescription": "부드럽고 깨끗한 곡물 향",
    "image": "https://example.com/bison_vodka.jpg"
},
{
    "name": "쿠바 리브레 럼",
    "type": "럼",
    "category": "증류주",
    "subCategory": "럼",
    "origin": "쿠바",
    "alcohol": 38,
    "rating": 4.5,
    "description": "쿠바산 럼으로, 진한 캐러멜과 스파이스가 조화를 이루는 매력적인 맛입니다.",
    "price": 40000,
    "tasteDescription": "캐러멜, 스파이스",
    "image": "https://example.com/cuba_libre_rum.jpg"
},
{
    "name": "칼라스 리큐어",
    "type": "리큐어",
    "category": "증류주",
    "subCategory": "리큐어",
    "origin": "이탈리아",
    "alcohol": 20,
    "rating": 4.2,
    "description": "허브와 약초의 풍미가 돋보이는 이탈리아산 리큐어.",
    "price": 28000,
    "tasteDescription": "허브, 약초",
    "image": "https://example.com/calas_liqueur.jpg"
},
{
    "name": "블루라군 진",
    "type": "진",
    "category": "증류주",
    "subCategory": "진",
    "origin": "영국",
    "alcohol": 47,
    "rating": 4.5,
    "description": "상쾌한 시트러스와 진베리의 풍미가 돋보이는 영국산 프리미엄 진.",
    "price": 48000,
    "tasteDescription": "시트러스, 진베리",
    "image": "https://example.com/blue_lagoon_gin.jpg"
},
{
    "name": "페레라보드카",
    "type": "보드카",
    "category": "증류주",
    "subCategory": "보드카",
    "origin": "러시아",
    "alcohol": 40,
    "rating": 4.5,
    "description": "러시아산 프리미엄 보드카로, 깔끔하고 부드러운 맛이 특징입니다.",
    "price": 45000,
    "tasteDescription": "깔끔하고 부드러운 맛",
    "image": "https://example.com/ferrera_vodka.jpg"
},
{
    "name": "콘다도 데 하이타",
    "type": "브랜디",
    "category": "증류주",
    "subCategory": "브랜디",
    "origin": "스페인",
    "alcohol": 38,
    "rating": 4.6,
    "description": "스페인의 프리미엄 브랜디로, 깊은 과일 향과 오크가 조화롭게 어우러집니다.",
    "price": 48000,
    "tasteDescription": "과일, 오크",
    "image": "https://example.com/condado_brandy.jpg"
},
      //혼성주 50개(46개 넣어야함.)
      {
        name: "모히또",
        type: "칵테일",
        category: "혼성주",
        subCategory: "칵테일",
        origin: "쿠바",
        alcohol: 13,
        rating: 4.7,
        description: "민트와 라임, 설탕의 조화로 시원하고 상쾌한 맛.",
        price: 12000,
        tasteDescription: "민트와 라임의 상쾌함",
        image: "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA3MTVfODgg%2FMDAxNjI2MzMyMTg4Njg2.0LiDNhcV3W4uv2UKF0_kHmP6SyQabowEUBlcWU-IqXog.JlKWIC-VljAyrfD4erXMBuX3JgoFnFdyByhEEhgf9HQg.PNG.golmok_salon02%2Fimage.png&type=sc960_832"
      },
      {
        name: "다이퀴리",
        type: "칵테일",
        category: "혼성주",
        subCategory: "칵테일",
        origin: "쿠바",
        alcohol: 15,
        rating: 4.5,
        description: "라임 주스와 설탕이 더해진 럼 기반의 칵테일.",
        price: 15000,
        tasteDescription: "상큼한 라임과 달콤함",
        image: "https://i.namu.wiki/i/UnGhC8V5N3ycEpjmOP1ABm-pfx-lIiD_zvyxgHg-BpBSe0EBiciA3EdF1ocszy-Cx5IkQ3nwFg-wYtdN_Vudsw.webp"
      },
      {
        name: "니카 블랙 하이볼",
        type: "하이볼",
        category: "혼성주",
        subCategory: "하이볼",
        origin: "일본",
        alcohol: 9,
        rating: 4.4,
        description: "진한 몰트 맛과 상쾌한 진저의 조화.",
        price: 11000,
        tasteDescription: "몰트와 진저의 상쾌함",
        image: "https://mblogthumb-phinf.pstatic.net/MjAyNDA1MzBfMjg0/MDAxNzE3MDczNjE4NDAy.xAV366SefjwBF6F3SlAWcOY0gp6pg_TtNUJTfr3-AFMg.Sq0x4uPCUPzMasc7yKUv58MahxS_B2MlDIc3FBUR4gQg.JPEG/SE-37d2fc86-9990-4e2e-b573-f44ede37e198.jpg?type=w800"
      },
      {
        name: "산토리 가쿠빈 하이볼",
        type: "하이볼",
        category: "혼성주",
        subCategory: "하이볼",
        origin: "일본",
        alcohol: 10,
        rating: 4.5,
        description: "청량한 탄산과 부드러운 위스키 맛의 조화.",
        price: 10000,
        tasteDescription: "탄산과 위스키의 청량함",
        image: "https://cafe24.poxo.com/ec01/yms2310/HOvhRhvOk+Cp2KY4JuusAkTsbIYINUK2VSIGmcb5x6rWbiVFKFLJiOWiKTlmhPfGrqEqVOht/QNAz2W0Hrz3hg==/_/web/product/big/20191123/1d0cb3877d527ee5fd045e772a98bf78.jpg"
      },
      //전통주(아직 하나도 없음)
    ];
  }
  