function getFoodData() {
    return [
       // 한식 10 items
    {
      name: "비빔밥",
      type: "한식",
      category: "한식",
      subCategory: "밥 요리",
      origin: "한국",
      ingredients: "밥, 고추장, 나물, 계란, 참기름",
      rating: 4.7,
      description: "다양한 나물과 고추장이 어우러진 한국 전통 음식.",
      price: 10000,
      tasteDescription: "매콤하고 고소한 맛",
      image: "https://image.url/bibimbap.jpg"
    },
    {
      name: "김치찌개",
      type: "한식",
      category: "한식",
      subCategory: "찌개 요리",
      origin: "한국",
      ingredients: "김치, 돼지고기, 두부, 고추장",
      rating: 4.8,
      description: "김치와 돼지고기로 끓인 한국의 대표 찌개.",
      price: 9000,
      tasteDescription: "매콤하고 칼칼한 맛",
      image: "https://image.url/kimchijjigae.jpg"
    },
    {
      name: "불고기",
      type: "한식",
      category: "한식",
      subCategory: "고기 요리",
      origin: "한국",
      ingredients: "소고기, 간장, 설탕, 마늘, 참기름",
      rating: 4.9,
      description: "달콤한 간장 양념에 재운 소고기를 구운 한국 전통 요리.",
      price: 18000,
      tasteDescription: "달콤하고 짭조름한 맛",
      image: "https://image.url/bulgogi.jpg"
    },
    {
      name: "된장찌개",
      type: "한식",
      category: "한식",
      subCategory: "찌개 요리",
      origin: "한국",
      ingredients: "된장, 두부, 애호박, 감자, 고추",
      rating: 4.6,
      description: "된장으로 끓인 구수한 한국 전통 찌개.",
      price: 8000,
      tasteDescription: "구수한 된장 맛",
      image: "https://image.url/soybeanstew.jpg"
    },
    {
      name: "닭갈비",
      type: "한식",
      category: "한식",
      subCategory: "고기 요리",
      origin: "한국",
      ingredients: "닭고기, 고추장, 양배추, 고구마, 떡",
      rating: 4.7,
      description: "매콤달콤한 양념에 볶아낸 닭고기 요리.",
      price: 17000,
      tasteDescription: "매콤하고 달콤한 맛",
      image: "https://image.url/dakgalbi.jpg"
    },
    {
      name: "잡채",
      type: "한식",
      category: "한식",
      subCategory: "볶음 요리",
      origin: "한국",
      ingredients: "당면, 소고기, 시금치, 양파, 당근, 간장",
      rating: 4.8,
      description: "당면과 채소를 간장 소스로 볶아낸 요리.",
      price: 13000,
      tasteDescription: "달콤하고 짭조름한 맛",
      image: "https://image.url/japchae.jpg"
    },
    {
      name: "떡볶이",
      type: "한식",
      category: "한식",
      subCategory: "분식",
      origin: "한국",
      ingredients: "떡, 고추장, 어묵, 양배추, 대파",
      rating: 4.6,
      description: "매콤달콤한 소스에 떡을 볶아 만든 한국 대표 간식.",
      price: 5000,
      tasteDescription: "매콤하고 달콤한 맛",
      image: "https://image.url/tteokbokki.jpg"
    },
    {
      name: "삼계탕",
      type: "한식",
      category: "한식",
      subCategory: "탕 요리",
      origin: "한국",
      ingredients: "닭고기, 인삼, 대추, 찹쌀",
      rating: 4.7,
      description: "건강식으로 유명한 닭 한 마리를 푹 고아 만든 탕 요리.",
      price: 15000,
      tasteDescription: "담백하고 영양가 있는 맛",
      image: "https://image.url/samgyetang.jpg"
    },
    {
      name: "파전",
      type: "한식",
      category: "한식",
      subCategory: "전 요리",
      origin: "한국",
      ingredients: "밀가루, 파, 해물, 계란",
      rating: 4.6,
      description: "파와 해물을 넣어 부쳐낸 한국식 전 요리.",
      price: 12000,
      tasteDescription: "바삭하고 고소한 맛",
      image: "https://image.url/pajeon.jpg"
    },

      {
        name: "갈비찜",
        type: "한식",
        category: "한식",
        subCategory: "고기 요리",
        origin: "한국",
        ingredients: "소갈비, 간장, 설탕, 마늘, 생강, 참기름",
        rating: 4.8,
        description: "부드러운 소갈비에 짭조름한 간장 양념이 배어든 한국 전통 요리.",
        price: 35000,
        tasteDescription: "짭짤하고 달콤한 간장 양념",
        image: "https://image.url/galbijjim.jpg"
      },

      //일식 11 items
 {
  name: "스시 모리아와세",
  type: "일식",
  category: "일식",
  subCategory: "스시",
  origin: "일본",
  ingredients: "참치, 연어, 광어, 밥, 간장, 와사비",
  rating: 4.9,
  description: "신선한 생선과 부드러운 밥이 어우러진 일식 스시 세트.",
  price: 25000,
  tasteDescription: "신선한 생선과 간장의 감칠맛",
  image: "https://image.url/sushi.jpg"
},
{
  name: "라멘",
  type: "일식",
  category: "일식",
  subCategory: "면 요리",
  origin: "일본",
  ingredients: "면, 돼지고기, 계란, 파, 간장",
  rating: 4.6,
  description: "간장 베이스 국물과 돼지고기가 어우러진 일본 전통 라멘.",
  price: 15000,
  tasteDescription: "짭짤한 간장 국물과 부드러운 고기",
  image: "https://image.url/ramen.jpg"
},
{
  name: "오코노미야끼",
  type: "일식",
  category: "일식",
  subCategory: "전 요리",
  origin: "일본",
  ingredients: "밀가루, 양배추, 돼지고기, 가쓰오부시, 마요네즈",
  rating: 4.7,
  description: "일본식 부침개로, 다양한 재료를 섞어 구워낸 요리.",
  price: 12000,
  tasteDescription: "짭짤하고 고소한 맛",
  image: "https://image.url/okonomiyaki.jpg"
},
{
  name: "가츠동",
  type: "일식",
  category: "일식",
  subCategory: "덮밥 요리",
  origin: "일본",
  ingredients: "밥, 돈까스, 계란, 양파, 간장 소스",
  rating: 4.7,
  description: "돈까스와 계란을 간장 소스에 졸여 만든 일본식 덮밥.",
  price: 12000,
  tasteDescription: "짭짤하고 고소한 돈까스와 밥의 조화",
  image: "https://image.url/katsudon.jpg"
},
{
  name: "돈부리",
  type: "일식",
  category: "일식",
  subCategory: "덮밥 요리",
  origin: "일본",
  ingredients: "밥, 소고기, 간장, 설탕, 양파",
  rating: 4.8,
  description: "간장 소스에 졸인 소고기를 밥 위에 얹어낸 덮밥 요리.",
  price: 13000,
  tasteDescription: "짭짤하고 달콤한 맛",
  image: "https://image.url/donburi.jpg"
},
{
  name: "우동",
  type: "일식",
  category: "일식",
  subCategory: "면 요리",
  origin: "일본",
  ingredients: "우동 면, 국물, 대파, 가쓰오부시",
  rating: 4.6,
  description: "굵은 면발과 깊은 국물 맛이 어우러진 일본식 면 요리.",
  price: 10000,
  tasteDescription: "담백한 국물과 쫄깃한 면발",
  image: "https://image.url/udon.jpg"
},
{
  name: "덴푸라",
  type: "일식",
  category: "일식",
  subCategory: "튀김 요리",
  origin: "일본",
  ingredients: "새우, 오징어, 채소, 밀가루, 튀김가루",
  rating: 4.8,
  description: "바삭하게 튀긴 새우와 채소를 곁들인 튀김 요리.",
  price: 14000,
  tasteDescription: "바삭하고 고소한 맛",
  image: "https://image.url/tempura.jpg"
},
{
  name: "타코야끼",
  type: "일식",
  category: "일식",
  subCategory: "분식",
  origin: "일본",
  ingredients: "밀가루 반죽, 문어, 마요네즈, 가쓰오부시",
  rating: 4.7,
  description: "문어와 반죽을 구워내어 소스를 얹은 일본 대표 간식.",
  price: 8000,
  tasteDescription: "짭짤하고 고소한 맛",
  image: "https://image.url/takoyaki.jpg"
},
{
  name: "규동",
  type: "일식",
  category: "일식",
  subCategory: "덮밥 요리",
  origin: "일본",
  ingredients: "소고기, 양파, 간장, 밥",
  rating: 4.7,
  description: "얇게 썬 소고기를 양파와 함께 간장 소스에 조린 일본식 덮밥.",
  price: 11000,
  tasteDescription: "짭짤하고 달콤한 맛",
  image: "https://image.url/gyudon.jpg"
},
{
  name: "스키야키",
  type: "일식",
  category: "일식",
  subCategory: "전골 요리",
  origin: "일본",
  ingredients: "소고기, 간장, 설탕, 채소",
  rating: 4.9,
  description: "얇게 썬 소고기와 채소를 달콤한 간장 소스에 졸인 전골 요리.",
  price: 20000,
  tasteDescription: "달콤하고 짭짤한 맛",
  image: "https://image.url/sukiyaki.jpg"
},

// 중식 - 10 items
{
  name: "짜장면",
  type: "중식",
  category: "중식",
  subCategory: "면 요리",
  origin: "중국",
  ingredients: "면, 춘장, 돼지고기, 양파, 호박",
  rating: 4.5,
  description: "춘장을 베이스로 만든 달콤한 중국식 면 요리.",
  price: 6000,
  tasteDescription: "달콤하고 짭짤한 춘장 소스",
  image: "https://image.url/jjajangmyeon.jpg"
},
{
  name: "탕수육",
  type: "중식",
  category: "중식",
  subCategory: "고기 요리",
  origin: "중국",
  ingredients: "돼지고기, 튀김가루, 간장, 식초, 설탕",
  rating: 4.6,
  description: "바삭한 돼지고기에 새콤달콤한 소스를 얹은 중식 요리.",
  price: 15000,
  tasteDescription: "새콤달콤하고 바삭한 식감",
  image: "https://image.url/tangsuyuk.jpg"
},
{
  name: "꿔바로우",
  type: "중식",
  category: "중식",
  subCategory: "고기 요리",
  origin: "중국",
  ingredients: "돼지고기, 튀김가루, 식초, 설탕, 간장",
  rating: 4.8,
  description: "바삭하게 튀긴 돼지고기에 새콤달콤한 소스를 얹은 요리.",
  price: 20000,
  tasteDescription: "새콤달콤하고 바삭한 식감",
  image: "https://image.url/guobaorou.jpg"
},
{
  name: "짬뽕",
  type: "중식",
  category: "중식",
  subCategory: "면 요리",
  origin: "중국",
  ingredients: "면, 해산물, 고추기름, 양파, 고추",
  rating: 4.7,
  description: "매콤한 국물에 해산물이 어우러진 중국식 면 요리.",
  price: 7000,
  tasteDescription: "매콤하고 시원한 맛",
  image: "https://image.url/jjamppong.jpg"
},
{
  name: "마파두부",
  type: "중식",
  category: "중식",
  subCategory: "두부 요리",
  origin: "중국",
  ingredients: "두부, 다진 돼지고기, 고추기름, 마늘, 생강",
  rating: 4.8,
  description: "두부와 다진 돼지고기를 매콤하게 볶아낸 중식 요리.",
  price: 12000,
  tasteDescription: "매콤하고 고소한 맛",
  image: "https://image.url/mapotofu.jpg"
},
{
  name: "볶음밥",
  type: "중식",
  category: "중식",
  subCategory: "밥 요리",
  origin: "중국",
  ingredients: "밥, 계란, 대파, 당근, 간장",
  rating: 4.6,
  description: "밥을 계란과 함께 간장 소스에 볶아낸 중식 요리.",
  price: 8000,
  tasteDescription: "고소하고 담백한 맛",
  image: "https://image.url/friedrice.jpg"
},
{
  name: "양장피",
  type: "중식",
  category: "중식",
  subCategory: "샐러드",
  origin: "중국",
  ingredients: "해산물, 계란, 오이, 당근, 겨자소스",
  rating: 4.7,
  description: "해산물과 채소를 겨자소스로 버무려낸 중식 샐러드.",
  price: 18000,
  tasteDescription: "매콤하고 새콤한 맛",
  image: "https://image.url/yangjangpi.jpg"
},
{
  name: "깐풍기",
  type: "중식",
  category: "중식",
  subCategory: "고기 요리",
  origin: "중국",
  ingredients: "닭고기, 튀김가루, 고추, 마늘, 간장",
  rating: 4.8,
  description: "바삭하게 튀긴 닭고기를 매콤한 소스에 버무린 중식 요리.",
  price: 19000,
  tasteDescription: "매콤하고 바삭한 맛",
  image: "https://image.url/kanpunggi.jpg"
},
{
  name: "고추잡채",
  type: "중식",
  category: "중식",
  subCategory: "고기 요리",
  origin: "중국",
  ingredients: "돼지고기, 피망, 고추, 간장, 마늘",
  rating: 4.7,
  description: "돼지고기와 고추를 간장 소스로 볶아낸 중식 요리.",
  price: 17000,
  tasteDescription: "짭짤하고 매콤한 맛",
  image: "https://image.url/pepperstirfry.jpg"
},
{
  name: "유린기",
  type: "중식",
  category: "중식",
  subCategory: "고기 요리",
  origin: "중국",
  ingredients: "닭고기, 튀김가루, 간장, 식초, 대파",
  rating: 4.8,
  description: "바삭한 닭고기에 새콤달콤한 소스를 얹은 중식 요리.",
  price: 20000,
  tasteDescription: "새콤달콤하고 바삭한 맛",
  image: "https://image.url/yurinji.jpg"
},

// 양식 (Western) - 10 items
{
  name: "피자 마르게리타",
  type: "이탈리안",
  category: "양식",
  subCategory: "피자",
  origin: "이탈리아",
  ingredients: "토마토, 모차렐라, 바질, 올리브유",
  rating: 4.7,
  description: "신선한 토마토와 모차렐라 치즈, 바질로 만든 전통 피자.",
  price: 18000,
  tasteDescription: "신선한 토마토와 치즈의 조화",
  image: "https://image.url/margherita.jpg"
},
{
  name: "파스타 카르보나라",
  type: "이탈리안",
  category: "양식",
  subCategory: "파스타",
  origin: "이탈리아",
  ingredients: "면, 베이컨, 계란, 치즈",
  rating: 4.9,
  description: "크림 없이 계란과 치즈로 만든 이탈리안 전통 파스타.",
  price: 16000,
  tasteDescription: "고소한 치즈와 베이컨의 풍미",
  image: "https://image.url/carbonara.jpg"
},
{
  name: "햄버거",
  type: "미국식",
  category: "양식",
  subCategory: "버거",
  origin: "미국",
  ingredients: "소고기 패티, 빵, 치즈, 양상추, 토마토, 소스",
  rating: 4.8,
  description: "신선한 재료로 만든 미국의 대표 패스트푸드.",
  price: 13000,
  tasteDescription: "고소한 패티와 신선한 채소의 조화",
  image: "https://image.url/burger.jpg"
},
{
  name: "스테이크",
  type: "미국식",
  category: "양식",
  subCategory: "고기 요리",
  origin: "미국",
  ingredients: "소고기, 소금, 후추, 버터",
  rating: 4.9,
  description: "고급 소고기를 소금과 후추로 간단하게 구워낸 요리.",
  price: 45000,
  tasteDescription: "고소하고 풍미 가득한 소고기",
  image: "https://image.url/steak.jpg"
},
{
  name: "파스타 볼로네제",
  type: "이탈리안",
  category: "양식",
  subCategory: "파스타",
  origin: "이탈리아",
  ingredients: "면, 토마토 소스, 소고기, 양파, 마늘",
  rating: 4.8,
  description: "풍부한 토마토 소스와 고기가 어우러진 이탈리안 파스타.",
  price: 15000,
  tasteDescription: "상큼한 토마토와 고소한 고기의 조화",
  image: "https://image.url/bolognese.jpg"
},
{
  name: "치킨 시저 샐러드",
  type: "미국식",
  category: "양식",
  subCategory: "샐러드",
  origin: "미국",
  ingredients: "닭가슴살, 로메인 상추, 파마산 치즈, 시저 드레싱",
  rating: 4.7,
  description: "담백한 닭가슴살과 신선한 채소로 만든 샐러드.",
  price: 12000,
  tasteDescription: "고소하고 상큼한 드레싱의 맛",
  image: "https://image.url/caesarsalad.jpg"
},
{
  name: "클럽 샌드위치",
  type: "미국식",
  category: "양식",
  subCategory: "샌드위치",
  origin: "미국",
  ingredients: "토스트, 닭가슴살, 베이컨, 양상추, 토마토, 마요네즈",
  rating: 4.8,
  description: "토스트에 신선한 재료를 곁들인 미국식 샌드위치.",
  price: 13000,
  tasteDescription: "고소한 닭가슴살과 베이컨의 조화",
  image: "https://image.url/clubsandwich.jpg"
},
{
  name: "감바스 알 아히요",
  type: "스페인식",
  category: "양식",
  subCategory: "해산물 요리",
  origin: "스페인",
  ingredients: "새우, 마늘, 올리브유, 고추",
  rating: 4.9,
  description: "올리브유에 마늘과 함께 새우를 볶아낸 스페인 요리.",
  price: 18000,
  tasteDescription: "향긋한 마늘과 새우의 풍미",
  image: "https://image.url/gambas.jpg"
},
{
  name: "로스트 비프",
  type: "영국식",
  category: "양식",
  subCategory: "고기 요리",
  origin: "영국",
  ingredients: "소고기, 감자, 당근, 그레이비 소스",
  rating: 4.8,
  description: "오븐에 구워낸 소고기와 채소를 곁들인 영국 요리.",
  price: 40000,
  tasteDescription: "고소하고 담백한 맛",
  image: "https://image.url/roastbeef.jpg"
},
{
  name: "퀘사디아",
  type: "멕시칸",
  category: "양식",
  subCategory: "타코",
  origin: "멕시코",
  ingredients: "토르티야, 치즈, 닭고기, 살사 소스",
  rating: 4.6,
  description: "바삭한 토르티야에 치즈와 닭고기를 넣고 구운 멕시코 음식.",
  price: 13000,
  tasteDescription: "고소하고 매콤한 맛",
  image: "https://image.url/quesadilla.jpg"
},

// 디저트 (Dessert) - 10 items
{
  name: "티라미수",
  type: "이탈리안",
  category: "디저트",
  subCategory: "케이크",
  origin: "이탈리아",
  ingredients: "마스카르포네 치즈, 에스프레소, 코코아 가루",
  rating: 4.8,
  description: "커피와 치즈가 어우러진 달콤한 이탈리안 디저트.",
  price: 7000,
  tasteDescription: "달콤하고 커피의 풍미가 느껴지는 맛",
  image: "https://image.url/tiramisu.jpg"
},
{
  name: "마카롱",
  type: "프렌치",
  category: "디저트",
  subCategory: "과자",
  origin: "프랑스",
  ingredients: "아몬드 가루, 설탕, 계란 흰자, 크림",
  rating: 4.7,
  description: "아몬드 가루로 만든 부드럽고 달콤한 프랑스식 과자.",
  price: 4000,
  tasteDescription: "달콤하고 부드러운 식감",
  image: "https://image.url/macaroon.jpg"
},
{
  name: "크레페",
  type: "프렌치",
  category: "디저트",
  subCategory: "크레페",
  origin: "프랑스",
  ingredients: "밀가루, 우유, 계란, 설탕, 버터",
  rating: 4.7,
  description: "얇고 부드러운 프랑스식 팬케이크에 달콤한 소스가 더해진 디저트.",
  price: 8000,
  tasteDescription: "달콤하고 부드러운 크레페와 소스",
  image: "https://image.url/crepe.jpg"
},
{
  name: "초콜릿 무스",
  type: "프렌치",
  category: "디저트",
  subCategory: "무스",
  origin: "프랑스",
  ingredients: "다크 초콜릿, 계란, 설탕, 크림",
  rating: 4.8,
  description: "부드럽고 진한 초콜릿 맛이 일품인 프랑스 디저트.",
  price: 8000,
  tasteDescription: "달콤하고 부드러운 초콜릿의 풍미",
  image: "https://image.url/chocolate_mousse.jpg"
},
{
  name: "애플파이",
  type: "미국식",
  category: "디저트",
  subCategory: "파이",
  origin: "미국",
  ingredients: "사과, 설탕, 계피, 밀가루, 버터",
  rating: 4.8,
  description: "버터와 밀가루 반죽에 달콤한 사과를 넣어 구운 미국식 파이.",
  price: 9000,
  tasteDescription: "달콤한 사과와 바삭한 파이의 조화",
  image: "https://image.url/applepie.jpg"
},
{
  name: "바클라바",
  type: "터키식",
  category: "디저트",
  subCategory: "패스트리",
  origin: "터키",
  ingredients: "필로 반죽, 견과류, 꿀, 설탕 시럽",
  rating: 4.8,
  description: "바삭한 반죽 사이에 견과류와 시럽을 넣어 만든 터키 디저트.",
  price: 10000,
  tasteDescription: "달콤하고 바삭한 맛",
  image: "https://image.url/baklava.jpg"
},
{
  name: "도너츠",
  type: "미국식",
  category: "디저트",
  subCategory: "베이커리",
  origin: "미국",
  ingredients: "밀가루, 설탕, 버터, 계란",
  rating: 4.7,
  description: "바삭하게 튀긴 반죽에 설탕을 입힌 달콤한 디저트.",
  price: 3000,
  tasteDescription: "달콤하고 바삭한 식감",
  image: "https://image.url/doughnut.jpg"
},
{
  name: "에끌레어",
  type: "프렌치",
  category: "디저트",
  subCategory: "베이커리",
  origin: "프랑스",
  ingredients: "밀가루, 계란, 초콜릿, 크림",
  rating: 4.8,
  description: "얇은 반죽 안에 달콤한 크림을 채우고 초콜릿을 덮은 디저트.",
  price: 5000,
  tasteDescription: "달콤하고 부드러운 크림과 초콜릿",
  image: "https://image.url/eclair.jpg"
},
{
  name: "판나코타",
  type: "이탈리안",
  category: "디저트",
  subCategory: "젤리",
  origin: "이탈리아",
  ingredients: "크림, 설탕, 바닐라, 젤라틴",
  rating: 4.7,
  description: "부드럽고 달콤한 크림으로 만든 이탈리안 젤리 디저트.",
  price: 8000,
  tasteDescription: "부드럽고 달콤한 크림 맛",
  image: "https://image.url/pannacotta.jpg"
},
{
  name: "치즈케이크",
  type: "미국식",
  category: "디저트",
  subCategory: "케이크",
  origin: "미국",
  ingredients: "크림치즈, 설탕, 계란, 버터, 과자 크러스트",
  rating: 4.9,
  description: "크림치즈와 설탕으로 만든 달콤하고 부드러운 케이크.",
  price: 10000,
  tasteDescription: "고소하고 부드러운 치즈의 맛",
  image: "https://image.url/cheesecake.jpg"
},
    ];
  }
